/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 53
#define LARGE_STATE_COUNT 5
#define SYMBOL_COUNT 44
#define ALIAS_COUNT 2
#define TOKEN_COUNT 29
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 1
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 6
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_comment = 1,
  anon_sym_DQUOTE = 2,
  aux_sym_string_token1 = 3,
  sym_escape = 4,
  sym_number = 5,
  sym_hex_color = 6,
  sym_css_var = 7,
  sym__ident = 8,
  sym_id = 9,
  sym_define_op = 10,
  anon_sym_PIPE = 11,
  anon_sym_DASH = 12,
  anon_sym_COLON = 13,
  sym_assign_op = 14,
  anon_sym_LPAREN = 15,
  anon_sym_RPAREN = 16,
  anon_sym_LPAREN2 = 17,
  anon_sym_COMMA = 18,
  sym_math_op = 19,
  sym_class = 20,
  sym_side = 21,
  sym_link_op = 22,
  sym_fanout = 23,
  anon_sym_LBRACE = 24,
  anon_sym_RBRACE = 25,
  anon_sym_LBRACK = 26,
  anon_sym_RBRACK = 27,
  anon_sym_SEMI = 28,
  sym_source_file = 29,
  sym__item = 30,
  sym_string = 31,
  sym_type_bars = 32,
  sym_property = 33,
  sym_params = 34,
  sym_assignment = 35,
  sym_call = 36,
  sym_group = 37,
  sym__expr_item = 38,
  sym_value_ident = 39,
  sym__punct = 40,
  aux_sym_source_file_repeat1 = 41,
  aux_sym_string_repeat1 = 42,
  aux_sym_params_repeat1 = 43,
  alias_sym_call_name = 44,
  alias_sym_type = 45,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_comment] = "comment",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_token1] = "string_token1",
  [sym_escape] = "escape",
  [sym_number] = "number",
  [sym_hex_color] = "hex_color",
  [sym_css_var] = "css_var",
  [sym__ident] = "_ident",
  [sym_id] = "id",
  [sym_define_op] = "define_op",
  [anon_sym_PIPE] = "|",
  [anon_sym_DASH] = "-",
  [anon_sym_COLON] = ":",
  [sym_assign_op] = "assign_op",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LPAREN2] = "(",
  [anon_sym_COMMA] = ",",
  [sym_math_op] = "math_op",
  [sym_class] = "class",
  [sym_side] = "side",
  [sym_link_op] = "link_op",
  [sym_fanout] = "fanout",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_SEMI] = ";",
  [sym_source_file] = "source_file",
  [sym__item] = "_item",
  [sym_string] = "string",
  [sym_type_bars] = "type_bars",
  [sym_property] = "property",
  [sym_params] = "params",
  [sym_assignment] = "assignment",
  [sym_call] = "call",
  [sym_group] = "group",
  [sym__expr_item] = "_expr_item",
  [sym_value_ident] = "value_ident",
  [sym__punct] = "_punct",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
  [aux_sym_params_repeat1] = "params_repeat1",
  [alias_sym_call_name] = "call_name",
  [alias_sym_type] = "type",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_comment] = sym_comment,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [sym_escape] = sym_escape,
  [sym_number] = sym_number,
  [sym_hex_color] = sym_hex_color,
  [sym_css_var] = sym_css_var,
  [sym__ident] = sym__ident,
  [sym_id] = sym_id,
  [sym_define_op] = sym_define_op,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_COLON] = anon_sym_COLON,
  [sym_assign_op] = sym_assign_op,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LPAREN2] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [sym_math_op] = sym_math_op,
  [sym_class] = sym_class,
  [sym_side] = sym_side,
  [sym_link_op] = sym_link_op,
  [sym_fanout] = sym_fanout,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [sym_source_file] = sym_source_file,
  [sym__item] = sym__item,
  [sym_string] = sym_string,
  [sym_type_bars] = sym_type_bars,
  [sym_property] = sym_property,
  [sym_params] = sym_params,
  [sym_assignment] = sym_assignment,
  [sym_call] = sym_call,
  [sym_group] = sym_group,
  [sym__expr_item] = sym__expr_item,
  [sym_value_ident] = sym_value_ident,
  [sym__punct] = sym__punct,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
  [aux_sym_params_repeat1] = aux_sym_params_repeat1,
  [alias_sym_call_name] = alias_sym_call_name,
  [alias_sym_type] = alias_sym_type,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_escape] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_hex_color] = {
    .visible = true,
    .named = true,
  },
  [sym_css_var] = {
    .visible = true,
    .named = true,
  },
  [sym__ident] = {
    .visible = false,
    .named = true,
  },
  [sym_id] = {
    .visible = true,
    .named = true,
  },
  [sym_define_op] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_assign_op] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN2] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [sym_math_op] = {
    .visible = true,
    .named = true,
  },
  [sym_class] = {
    .visible = true,
    .named = true,
  },
  [sym_side] = {
    .visible = true,
    .named = true,
  },
  [sym_link_op] = {
    .visible = true,
    .named = true,
  },
  [sym_fanout] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__item] = {
    .visible = false,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_type_bars] = {
    .visible = true,
    .named = true,
  },
  [sym_property] = {
    .visible = true,
    .named = true,
  },
  [sym_params] = {
    .visible = true,
    .named = true,
  },
  [sym_assignment] = {
    .visible = true,
    .named = true,
  },
  [sym_call] = {
    .visible = true,
    .named = true,
  },
  [sym_group] = {
    .visible = true,
    .named = true,
  },
  [sym__expr_item] = {
    .visible = false,
    .named = true,
  },
  [sym_value_ident] = {
    .visible = true,
    .named = true,
  },
  [sym__punct] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_params_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_call_name] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_type] = {
    .visible = true,
    .named = true,
  },
};

enum ts_field_identifiers {
  field_name = 1,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_name] = "name",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [2] = {.index = 0, .length = 1},
  [3] = {.index = 0, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [0] = sym_value_ident,
  },
  [2] = {
    [0] = sym_property,
  },
  [3] = {
    [0] = sym_value_ident,
  },
  [4] = {
    [0] = alias_sym_call_name,
  },
  [5] = {
    [1] = alias_sym_type,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 23,
  [29] = 22,
  [30] = 30,
  [31] = 16,
  [32] = 32,
  [33] = 33,
  [34] = 12,
  [35] = 7,
  [36] = 10,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 38,
  [42] = 39,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
};

static const TSCharacterRange sym_math_op_character_set_1[] = {
  {'!', '!'}, {'%', '%'}, {'*', '+'}, {'-', '-'}, {'/', '/'}, {':', ':'}, {'<', '?'}, {'^', '^'},
  {'~', '~'},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(25);
      ADVANCE_MAP(
        '"', 29,
        '#', 17,
        '&', 72,
        '(', 55,
        ')', 56,
        '+', 6,
        ',', 58,
        '-', 52,
        '.', 13,
        '/', 8,
        ':', 53,
        ';', 77,
        '=', 54,
        '[', 75,
        '\\', 11,
        ']', 76,
        'o', 42,
        '{', 73,
        '|', 50,
        '}', 74,
        '~', 71,
        '*', 7,
        '<', 7,
        '>', 7,
      );
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(23);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(34);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(46);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(1);
      if (lookahead == '"') ADVANCE(29);
      if (lookahead == '/') ADVANCE(31);
      if (lookahead == '\\') ADVANCE(11);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(30);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(32);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        '"', 29,
        '#', 17,
        '(', 55,
        ')', 56,
        '+', 60,
        ',', 58,
        '-', 59,
        '.', 12,
        '/', 61,
        ':', 63,
      );
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(4);
      if (lookahead == '!' ||
          lookahead == '%' ||
          lookahead == '*' ||
          ('<' <= lookahead && lookahead <= '?') ||
          lookahead == '^' ||
          lookahead == '~') ADVANCE(62);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(34);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(46);
      END_STATE();
    case 3:
      ADVANCE_MAP(
        '"', 29,
        '#', 17,
        '(', 57,
        ')', 56,
        '+', 60,
        ',', 58,
        '-', 59,
        '.', 12,
        '/', 61,
        ':', 63,
        '|', 49,
      );
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(3);
      if (lookahead == '!' ||
          lookahead == '%' ||
          lookahead == '*' ||
          ('<' <= lookahead && lookahead <= '?') ||
          lookahead == '^' ||
          lookahead == '~') ADVANCE(62);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(34);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(46);
      END_STATE();
    case 4:
      ADVANCE_MAP(
        '"', 29,
        '#', 17,
        '(', 57,
        ')', 56,
        '+', 60,
        ',', 58,
        '-', 59,
        '.', 12,
        '/', 61,
        ':', 63,
      );
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(4);
      if (lookahead == '!' ||
          lookahead == '%' ||
          lookahead == '*' ||
          ('<' <= lookahead && lookahead <= '?') ||
          lookahead == '^' ||
          lookahead == '~') ADVANCE(62);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(34);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(46);
      END_STATE();
    case 5:
      if (lookahead == '#') ADVANCE(21);
      if (lookahead == '-') ADVANCE(51);
      if (lookahead == '/') ADVANCE(8);
      if (lookahead == ':') ADVANCE(9);
      if (lookahead == '|') ADVANCE(49);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(5);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(46);
      END_STATE();
    case 6:
      ADVANCE_MAP(
        '-', 70,
        '.', 12,
        '|', 10,
        '~', 71,
        '*', 7,
        '+', 7,
        '<', 7,
        '>', 7,
        'o', 7,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(34);
      END_STATE();
    case 7:
      if (lookahead == '-') ADVANCE(70);
      if (lookahead == '|') ADVANCE(10);
      if (lookahead == '~') ADVANCE(71);
      if (lookahead == '*' ||
          lookahead == '+' ||
          lookahead == '<' ||
          lookahead == '>' ||
          lookahead == 'o') ADVANCE(7);
      END_STATE();
    case 8:
      if (lookahead == '/') ADVANCE(28);
      END_STATE();
    case 9:
      if (lookahead == ':') ADVANCE(48);
      END_STATE();
    case 10:
      if (lookahead == '|') ADVANCE(71);
      END_STATE();
    case 11:
      if (lookahead == '"' ||
          lookahead == '\\' ||
          lookahead == 'n' ||
          lookahead == 't') ADVANCE(33);
      END_STATE();
    case 12:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(35);
      END_STATE();
    case 13:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(35);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 14:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(37);
      END_STATE();
    case 15:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(36);
      END_STATE();
    case 16:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(14);
      END_STATE();
    case 17:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(16);
      END_STATE();
    case 18:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(39);
      END_STATE();
    case 19:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 20:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 21:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 22:
      if (eof) ADVANCE(25);
      ADVANCE_MAP(
        '"', 29,
        '#', 17,
        '&', 72,
        '(', 55,
        '+', 6,
        ',', 58,
        '-', 69,
        '.', 13,
        '/', 8,
        ':', 53,
        ';', 77,
        '=', 54,
        '[', 75,
        ']', 76,
        'o', 42,
        '{', 73,
        '|', 50,
        '}', 74,
        '~', 71,
        '*', 7,
        '<', 7,
        '>', 7,
      );
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(24);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(34);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(46);
      END_STATE();
    case 23:
      if (eof) ADVANCE(25);
      ADVANCE_MAP(
        '"', 29,
        '#', 17,
        '&', 72,
        '(', 57,
        ')', 56,
        '+', 6,
        ',', 58,
        '-', 52,
        '.', 13,
        '/', 8,
        ':', 20,
        ';', 77,
        '=', 54,
        '[', 75,
        '\\', 11,
        ']', 76,
        'o', 42,
        '{', 73,
        '|', 50,
        '}', 74,
        '~', 71,
        '*', 7,
        '<', 7,
        '>', 7,
      );
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(23);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(34);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(46);
      END_STATE();
    case 24:
      if (eof) ADVANCE(25);
      ADVANCE_MAP(
        '"', 29,
        '#', 17,
        '&', 72,
        '(', 57,
        '+', 6,
        ',', 58,
        '-', 69,
        '.', 13,
        '/', 8,
        ':', 20,
        ';', 77,
        '=', 54,
        '[', 75,
        ']', 76,
        'o', 42,
        '{', 73,
        '|', 50,
        '}', 74,
        '~', 71,
        '*', 7,
        '<', 7,
        '>', 7,
      );
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(24);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(34);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(46);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '"' ||
          lookahead == '\\') ADVANCE(28);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(26);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_comment);
      if (set_contains(sym_math_op_character_set_1, 9, lookahead)) ADVANCE(27);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(28);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '/') ADVANCE(31);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(30);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '"' &&
          lookahead != '\\' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(32);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '/') ADVANCE(26);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '"' &&
          lookahead != '\\' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(32);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '"' &&
          lookahead != '\\' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(32);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_escape);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(12);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(34);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(35);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_hex_color);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_hex_color);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(38);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_hex_color);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(18);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_hex_color);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(15);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_css_var);
      if (lookahead == 'o') ADVANCE(40);
      if (lookahead == '*' ||
          lookahead == '+' ||
          lookahead == '<' ||
          lookahead == '>') ADVANCE(71);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_css_var);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym__ident);
      if (lookahead == '-') ADVANCE(44);
      if (lookahead == 'o') ADVANCE(42);
      if (lookahead == '|') ADVANCE(10);
      if (lookahead == '~') ADVANCE(71);
      if (lookahead == '*' ||
          lookahead == '+' ||
          lookahead == '<' ||
          lookahead == '>') ADVANCE(7);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(46);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym__ident);
      if (lookahead == '-') ADVANCE(45);
      if (lookahead == 'o') ADVANCE(45);
      if (lookahead == '*' ||
          lookahead == '+' ||
          lookahead == '<' ||
          lookahead == '>') ADVANCE(71);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(46);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym__ident);
      if (lookahead == '-') ADVANCE(43);
      if (lookahead == 'o') ADVANCE(45);
      if (lookahead == '*' ||
          lookahead == '+' ||
          lookahead == '<' ||
          lookahead == '>') ADVANCE(71);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(46);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym__ident);
      if (lookahead == 'o') ADVANCE(45);
      if (lookahead == '*' ||
          lookahead == '+' ||
          lookahead == '<' ||
          lookahead == '>') ADVANCE(71);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(46);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym__ident);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(46);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_id);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_define_op);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_PIPE);
      if (lookahead == '|') ADVANCE(71);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (lookahead == '-') ADVANCE(67);
      if (lookahead == '.') ADVANCE(12);
      if (lookahead == '*' ||
          lookahead == '+' ||
          lookahead == '<' ||
          lookahead == '>' ||
          lookahead == 'o') ADVANCE(71);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(34);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_COLON);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_assign_op);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_LPAREN2);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_math_op);
      if (lookahead == '-') ADVANCE(64);
      if (lookahead == '.') ADVANCE(12);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(34);
      if (lookahead == '!' ||
          lookahead == '%' ||
          lookahead == '*' ||
          lookahead == '+' ||
          ('/' <= lookahead && lookahead <= ':') ||
          ('<' <= lookahead && lookahead <= '?') ||
          lookahead == '^' ||
          lookahead == '~') ADVANCE(62);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_math_op);
      if (lookahead == '.') ADVANCE(12);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(34);
      if (lookahead == '!' ||
          lookahead == '%' ||
          lookahead == '*' ||
          lookahead == '+' ||
          ('-' <= lookahead && lookahead <= ':') ||
          ('<' <= lookahead && lookahead <= '?') ||
          lookahead == '^' ||
          lookahead == '~') ADVANCE(62);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_math_op);
      if (lookahead == '/') ADVANCE(27);
      if (set_contains(sym_math_op_character_set_1, 9, lookahead)) ADVANCE(62);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_math_op);
      if (set_contains(sym_math_op_character_set_1, 9, lookahead)) ADVANCE(62);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_math_op);
      if (set_contains(sym_math_op_character_set_1, 9, lookahead)) ADVANCE(62);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_math_op);
      if (set_contains(sym_math_op_character_set_1, 9, lookahead)) ADVANCE(62);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_class);
      if (lookahead == '.') ADVANCE(19);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_side);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_link_op);
      if (lookahead == '-') ADVANCE(71);
      if (lookahead == 'o') ADVANCE(40);
      if (lookahead == '*' ||
          lookahead == '+' ||
          lookahead == '<' ||
          lookahead == '>') ADVANCE(71);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_link_op);
      if (lookahead == '-') ADVANCE(71);
      if (lookahead == '*' ||
          lookahead == '+' ||
          lookahead == '<' ||
          lookahead == '>' ||
          lookahead == 'o') ADVANCE(71);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_link_op);
      if (lookahead == '-') ADVANCE(67);
      if (lookahead == '.') ADVANCE(12);
      if (lookahead == '*' ||
          lookahead == '+' ||
          lookahead == '<' ||
          lookahead == '>' ||
          lookahead == 'o') ADVANCE(71);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(34);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_link_op);
      if (lookahead == '-') ADVANCE(68);
      if (lookahead == '*' ||
          lookahead == '+' ||
          lookahead == '<' ||
          lookahead == '>' ||
          lookahead == 'o') ADVANCE(71);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_link_op);
      if (lookahead == '*' ||
          lookahead == '+' ||
          lookahead == '<' ||
          lookahead == '>' ||
          lookahead == 'o') ADVANCE(71);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_fanout);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 24},
  [2] = {.lex_state = 24},
  [3] = {.lex_state = 24},
  [4] = {.lex_state = 22},
  [5] = {.lex_state = 24},
  [6] = {.lex_state = 24},
  [7] = {.lex_state = 24},
  [8] = {.lex_state = 24},
  [9] = {.lex_state = 24},
  [10] = {.lex_state = 24},
  [11] = {.lex_state = 24},
  [12] = {.lex_state = 24},
  [13] = {.lex_state = 24},
  [14] = {.lex_state = 24},
  [15] = {.lex_state = 24},
  [16] = {.lex_state = 24},
  [17] = {.lex_state = 24},
  [18] = {.lex_state = 24},
  [19] = {.lex_state = 24},
  [20] = {.lex_state = 24},
  [21] = {.lex_state = 3},
  [22] = {.lex_state = 3},
  [23] = {.lex_state = 3},
  [24] = {.lex_state = 3},
  [25] = {.lex_state = 3},
  [26] = {.lex_state = 3},
  [27] = {.lex_state = 3},
  [28] = {.lex_state = 3},
  [29] = {.lex_state = 3},
  [30] = {.lex_state = 2},
  [31] = {.lex_state = 3},
  [32] = {.lex_state = 3},
  [33] = {.lex_state = 3},
  [34] = {.lex_state = 3},
  [35] = {.lex_state = 3},
  [36] = {.lex_state = 3},
  [37] = {.lex_state = 1},
  [38] = {.lex_state = 1},
  [39] = {.lex_state = 1},
  [40] = {.lex_state = 5},
  [41] = {.lex_state = 1},
  [42] = {.lex_state = 1},
  [43] = {.lex_state = 5},
  [44] = {.lex_state = 5},
  [45] = {.lex_state = 5},
  [46] = {.lex_state = 3},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 3},
  [49] = {.lex_state = 3},
  [50] = {.lex_state = 3},
  [51] = {.lex_state = 3},
  [52] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym_escape] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_hex_color] = ACTIONS(1),
    [sym_css_var] = ACTIONS(1),
    [sym__ident] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [sym_assign_op] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LPAREN2] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [sym_class] = ACTIONS(1),
    [sym_side] = ACTIONS(1),
    [sym_link_op] = ACTIONS(1),
    [sym_fanout] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(47),
    [sym__item] = STATE(2),
    [sym_string] = STATE(2),
    [sym_type_bars] = STATE(2),
    [sym_property] = STATE(2),
    [sym_assignment] = STATE(2),
    [sym_call] = STATE(2),
    [sym_group] = STATE(2),
    [sym_value_ident] = STATE(2),
    [sym__punct] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_comment] = ACTIONS(3),
    [anon_sym_DQUOTE] = ACTIONS(7),
    [sym_number] = ACTIONS(9),
    [sym_hex_color] = ACTIONS(9),
    [sym_css_var] = ACTIONS(11),
    [sym__ident] = ACTIONS(13),
    [anon_sym_PIPE] = ACTIONS(15),
    [anon_sym_LPAREN2] = ACTIONS(17),
    [anon_sym_COMMA] = ACTIONS(9),
    [sym_class] = ACTIONS(9),
    [sym_side] = ACTIONS(9),
    [sym_link_op] = ACTIONS(11),
    [sym_fanout] = ACTIONS(9),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_RBRACE] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(9),
    [anon_sym_RBRACK] = ACTIONS(9),
    [anon_sym_SEMI] = ACTIONS(9),
  },
  [STATE(2)] = {
    [sym__item] = STATE(3),
    [sym_string] = STATE(3),
    [sym_type_bars] = STATE(3),
    [sym_property] = STATE(3),
    [sym_assignment] = STATE(3),
    [sym_call] = STATE(3),
    [sym_group] = STATE(3),
    [sym_value_ident] = STATE(3),
    [sym__punct] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(19),
    [sym_comment] = ACTIONS(3),
    [anon_sym_DQUOTE] = ACTIONS(7),
    [sym_number] = ACTIONS(21),
    [sym_hex_color] = ACTIONS(21),
    [sym_css_var] = ACTIONS(23),
    [sym__ident] = ACTIONS(13),
    [anon_sym_PIPE] = ACTIONS(15),
    [anon_sym_LPAREN2] = ACTIONS(17),
    [anon_sym_COMMA] = ACTIONS(21),
    [sym_class] = ACTIONS(21),
    [sym_side] = ACTIONS(21),
    [sym_link_op] = ACTIONS(23),
    [sym_fanout] = ACTIONS(21),
    [anon_sym_LBRACE] = ACTIONS(21),
    [anon_sym_RBRACE] = ACTIONS(21),
    [anon_sym_LBRACK] = ACTIONS(21),
    [anon_sym_RBRACK] = ACTIONS(21),
    [anon_sym_SEMI] = ACTIONS(21),
  },
  [STATE(3)] = {
    [sym__item] = STATE(3),
    [sym_string] = STATE(3),
    [sym_type_bars] = STATE(3),
    [sym_property] = STATE(3),
    [sym_assignment] = STATE(3),
    [sym_call] = STATE(3),
    [sym_group] = STATE(3),
    [sym_value_ident] = STATE(3),
    [sym__punct] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(25),
    [sym_comment] = ACTIONS(3),
    [anon_sym_DQUOTE] = ACTIONS(27),
    [sym_number] = ACTIONS(30),
    [sym_hex_color] = ACTIONS(30),
    [sym_css_var] = ACTIONS(33),
    [sym__ident] = ACTIONS(36),
    [anon_sym_PIPE] = ACTIONS(39),
    [anon_sym_LPAREN2] = ACTIONS(42),
    [anon_sym_COMMA] = ACTIONS(30),
    [sym_class] = ACTIONS(30),
    [sym_side] = ACTIONS(30),
    [sym_link_op] = ACTIONS(33),
    [sym_fanout] = ACTIONS(30),
    [anon_sym_LBRACE] = ACTIONS(30),
    [anon_sym_RBRACE] = ACTIONS(30),
    [anon_sym_LBRACK] = ACTIONS(30),
    [anon_sym_RBRACK] = ACTIONS(30),
    [anon_sym_SEMI] = ACTIONS(30),
  },
  [STATE(4)] = {
    [sym_params] = STATE(52),
    [ts_builtin_sym_end] = ACTIONS(45),
    [sym_comment] = ACTIONS(3),
    [anon_sym_DQUOTE] = ACTIONS(45),
    [sym_number] = ACTIONS(45),
    [sym_hex_color] = ACTIONS(45),
    [sym_css_var] = ACTIONS(47),
    [sym__ident] = ACTIONS(47),
    [anon_sym_PIPE] = ACTIONS(47),
    [anon_sym_COLON] = ACTIONS(49),
    [sym_assign_op] = ACTIONS(51),
    [anon_sym_LPAREN] = ACTIONS(53),
    [anon_sym_LPAREN2] = ACTIONS(47),
    [anon_sym_COMMA] = ACTIONS(45),
    [sym_class] = ACTIONS(45),
    [sym_side] = ACTIONS(45),
    [sym_link_op] = ACTIONS(47),
    [sym_fanout] = ACTIONS(45),
    [anon_sym_LBRACE] = ACTIONS(45),
    [anon_sym_RBRACE] = ACTIONS(45),
    [anon_sym_LBRACK] = ACTIONS(45),
    [anon_sym_RBRACK] = ACTIONS(45),
    [anon_sym_SEMI] = ACTIONS(45),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(59), 1,
      sym_assign_op,
    ACTIONS(57), 4,
      sym_css_var,
      sym__ident,
      anon_sym_PIPE,
      sym_link_op,
    ACTIONS(55), 14,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
      sym_number,
      sym_hex_color,
      anon_sym_LPAREN2,
      anon_sym_COMMA,
      sym_class,
      sym_side,
      sym_fanout,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_SEMI,
  [29] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(65), 1,
      sym_assign_op,
    ACTIONS(63), 4,
      sym_css_var,
      sym__ident,
      anon_sym_PIPE,
      sym_link_op,
    ACTIONS(61), 14,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
      sym_number,
      sym_hex_color,
      anon_sym_LPAREN2,
      anon_sym_COMMA,
      sym_class,
      sym_side,
      sym_fanout,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_SEMI,
  [58] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(69), 4,
      sym_css_var,
      sym__ident,
      anon_sym_PIPE,
      sym_link_op,
    ACTIONS(67), 14,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
      sym_number,
      sym_hex_color,
      anon_sym_LPAREN2,
      anon_sym_COMMA,
      sym_class,
      sym_side,
      sym_fanout,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_SEMI,
  [84] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(73), 4,
      sym_css_var,
      sym__ident,
      anon_sym_PIPE,
      sym_link_op,
    ACTIONS(71), 14,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
      sym_number,
      sym_hex_color,
      anon_sym_LPAREN2,
      anon_sym_COMMA,
      sym_class,
      sym_side,
      sym_fanout,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_SEMI,
  [110] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(77), 4,
      sym_css_var,
      sym__ident,
      anon_sym_PIPE,
      sym_link_op,
    ACTIONS(75), 14,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
      sym_number,
      sym_hex_color,
      anon_sym_LPAREN2,
      anon_sym_COMMA,
      sym_class,
      sym_side,
      sym_fanout,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_SEMI,
  [136] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(81), 4,
      sym_css_var,
      sym__ident,
      anon_sym_PIPE,
      sym_link_op,
    ACTIONS(79), 14,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
      sym_number,
      sym_hex_color,
      anon_sym_LPAREN2,
      anon_sym_COMMA,
      sym_class,
      sym_side,
      sym_fanout,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_SEMI,
  [162] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(85), 4,
      sym_css_var,
      sym__ident,
      anon_sym_PIPE,
      sym_link_op,
    ACTIONS(83), 14,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
      sym_number,
      sym_hex_color,
      anon_sym_LPAREN2,
      anon_sym_COMMA,
      sym_class,
      sym_side,
      sym_fanout,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_SEMI,
  [188] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(89), 4,
      sym_css_var,
      sym__ident,
      anon_sym_PIPE,
      sym_link_op,
    ACTIONS(87), 14,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
      sym_number,
      sym_hex_color,
      anon_sym_LPAREN2,
      anon_sym_COMMA,
      sym_class,
      sym_side,
      sym_fanout,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_SEMI,
  [214] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(93), 4,
      sym_css_var,
      sym__ident,
      anon_sym_PIPE,
      sym_link_op,
    ACTIONS(91), 14,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
      sym_number,
      sym_hex_color,
      anon_sym_LPAREN2,
      anon_sym_COMMA,
      sym_class,
      sym_side,
      sym_fanout,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_SEMI,
  [240] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(97), 4,
      sym_css_var,
      sym__ident,
      anon_sym_PIPE,
      sym_link_op,
    ACTIONS(95), 14,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
      sym_number,
      sym_hex_color,
      anon_sym_LPAREN2,
      anon_sym_COMMA,
      sym_class,
      sym_side,
      sym_fanout,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_SEMI,
  [266] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(101), 4,
      sym_css_var,
      sym__ident,
      anon_sym_PIPE,
      sym_link_op,
    ACTIONS(99), 14,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
      sym_number,
      sym_hex_color,
      anon_sym_LPAREN2,
      anon_sym_COMMA,
      sym_class,
      sym_side,
      sym_fanout,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_SEMI,
  [292] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(105), 4,
      sym_css_var,
      sym__ident,
      anon_sym_PIPE,
      sym_link_op,
    ACTIONS(103), 14,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
      sym_number,
      sym_hex_color,
      anon_sym_LPAREN2,
      anon_sym_COMMA,
      sym_class,
      sym_side,
      sym_fanout,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_SEMI,
  [318] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(109), 4,
      sym_css_var,
      sym__ident,
      anon_sym_PIPE,
      sym_link_op,
    ACTIONS(107), 14,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
      sym_number,
      sym_hex_color,
      anon_sym_LPAREN2,
      anon_sym_COMMA,
      sym_class,
      sym_side,
      sym_fanout,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_SEMI,
  [344] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(113), 4,
      sym_css_var,
      sym__ident,
      anon_sym_PIPE,
      sym_link_op,
    ACTIONS(111), 14,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
      sym_number,
      sym_hex_color,
      anon_sym_LPAREN2,
      anon_sym_COMMA,
      sym_class,
      sym_side,
      sym_fanout,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_SEMI,
  [370] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(117), 4,
      sym_css_var,
      sym__ident,
      anon_sym_PIPE,
      sym_link_op,
    ACTIONS(115), 14,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
      sym_number,
      sym_hex_color,
      anon_sym_LPAREN2,
      anon_sym_COMMA,
      sym_class,
      sym_side,
      sym_fanout,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_SEMI,
  [396] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(121), 4,
      sym_css_var,
      sym__ident,
      anon_sym_PIPE,
      sym_link_op,
    ACTIONS(119), 14,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
      sym_number,
      sym_hex_color,
      anon_sym_LPAREN2,
      anon_sym_COMMA,
      sym_class,
      sym_side,
      sym_fanout,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_SEMI,
  [422] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(123), 1,
      anon_sym_DQUOTE,
    ACTIONS(127), 1,
      sym__ident,
    ACTIONS(129), 1,
      anon_sym_RPAREN,
    ACTIONS(131), 1,
      anon_sym_LPAREN2,
    ACTIONS(133), 1,
      sym_math_op,
    ACTIONS(125), 5,
      sym_number,
      sym_hex_color,
      sym_css_var,
      anon_sym_COMMA,
      sym_side,
    STATE(24), 6,
      sym_string,
      sym_call,
      sym_group,
      sym__expr_item,
      sym_value_ident,
      aux_sym_params_repeat1,
  [456] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(123), 1,
      anon_sym_DQUOTE,
    ACTIONS(127), 1,
      sym__ident,
    ACTIONS(131), 1,
      anon_sym_LPAREN2,
    ACTIONS(137), 1,
      anon_sym_RPAREN,
    ACTIONS(139), 1,
      sym_math_op,
    ACTIONS(135), 5,
      sym_number,
      sym_hex_color,
      sym_css_var,
      anon_sym_COMMA,
      sym_side,
    STATE(25), 6,
      sym_string,
      sym_call,
      sym_group,
      sym__expr_item,
      sym_value_ident,
      aux_sym_params_repeat1,
  [490] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(123), 1,
      anon_sym_DQUOTE,
    ACTIONS(127), 1,
      sym__ident,
    ACTIONS(131), 1,
      anon_sym_LPAREN2,
    ACTIONS(143), 1,
      anon_sym_RPAREN,
    ACTIONS(145), 1,
      sym_math_op,
    ACTIONS(141), 5,
      sym_number,
      sym_hex_color,
      sym_css_var,
      anon_sym_COMMA,
      sym_side,
    STATE(22), 6,
      sym_string,
      sym_call,
      sym_group,
      sym__expr_item,
      sym_value_ident,
      aux_sym_params_repeat1,
  [524] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(123), 1,
      anon_sym_DQUOTE,
    ACTIONS(127), 1,
      sym__ident,
    ACTIONS(131), 1,
      anon_sym_LPAREN2,
    ACTIONS(139), 1,
      sym_math_op,
    ACTIONS(147), 1,
      anon_sym_RPAREN,
    ACTIONS(135), 5,
      sym_number,
      sym_hex_color,
      sym_css_var,
      anon_sym_COMMA,
      sym_side,
    STATE(25), 6,
      sym_string,
      sym_call,
      sym_group,
      sym__expr_item,
      sym_value_ident,
      aux_sym_params_repeat1,
  [558] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(149), 1,
      anon_sym_DQUOTE,
    ACTIONS(155), 1,
      sym__ident,
    ACTIONS(158), 1,
      anon_sym_RPAREN,
    ACTIONS(160), 1,
      anon_sym_LPAREN2,
    ACTIONS(163), 1,
      sym_math_op,
    ACTIONS(152), 5,
      sym_number,
      sym_hex_color,
      sym_css_var,
      anon_sym_COMMA,
      sym_side,
    STATE(25), 6,
      sym_string,
      sym_call,
      sym_group,
      sym__expr_item,
      sym_value_ident,
      aux_sym_params_repeat1,
  [592] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(123), 1,
      anon_sym_DQUOTE,
    ACTIONS(127), 1,
      sym__ident,
    ACTIONS(131), 1,
      anon_sym_LPAREN2,
    ACTIONS(168), 1,
      anon_sym_RPAREN,
    ACTIONS(170), 1,
      sym_math_op,
    ACTIONS(166), 5,
      sym_number,
      sym_hex_color,
      sym_css_var,
      anon_sym_COMMA,
      sym_side,
    STATE(27), 6,
      sym_string,
      sym_call,
      sym_group,
      sym__expr_item,
      sym_value_ident,
      aux_sym_params_repeat1,
  [626] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(123), 1,
      anon_sym_DQUOTE,
    ACTIONS(127), 1,
      sym__ident,
    ACTIONS(131), 1,
      anon_sym_LPAREN2,
    ACTIONS(139), 1,
      sym_math_op,
    ACTIONS(172), 1,
      anon_sym_RPAREN,
    ACTIONS(135), 5,
      sym_number,
      sym_hex_color,
      sym_css_var,
      anon_sym_COMMA,
      sym_side,
    STATE(25), 6,
      sym_string,
      sym_call,
      sym_group,
      sym__expr_item,
      sym_value_ident,
      aux_sym_params_repeat1,
  [660] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(123), 1,
      anon_sym_DQUOTE,
    ACTIONS(127), 1,
      sym__ident,
    ACTIONS(131), 1,
      anon_sym_LPAREN2,
    ACTIONS(176), 1,
      anon_sym_RPAREN,
    ACTIONS(178), 1,
      sym_math_op,
    ACTIONS(174), 5,
      sym_number,
      sym_hex_color,
      sym_css_var,
      anon_sym_COMMA,
      sym_side,
    STATE(29), 6,
      sym_string,
      sym_call,
      sym_group,
      sym__expr_item,
      sym_value_ident,
      aux_sym_params_repeat1,
  [694] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(123), 1,
      anon_sym_DQUOTE,
    ACTIONS(127), 1,
      sym__ident,
    ACTIONS(131), 1,
      anon_sym_LPAREN2,
    ACTIONS(139), 1,
      sym_math_op,
    ACTIONS(180), 1,
      anon_sym_RPAREN,
    ACTIONS(135), 5,
      sym_number,
      sym_hex_color,
      sym_css_var,
      anon_sym_COMMA,
      sym_side,
    STATE(25), 6,
      sym_string,
      sym_call,
      sym_group,
      sym__expr_item,
      sym_value_ident,
      aux_sym_params_repeat1,
  [728] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(182), 1,
      anon_sym_LPAREN,
    ACTIONS(47), 2,
      anon_sym_LPAREN2,
      sym_math_op,
    ACTIONS(45), 8,
      anon_sym_DQUOTE,
      sym_number,
      sym_hex_color,
      sym_css_var,
      sym__ident,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_side,
  [749] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(105), 1,
      sym_math_op,
    ACTIONS(103), 9,
      anon_sym_DQUOTE,
      sym_number,
      sym_hex_color,
      sym_css_var,
      sym__ident,
      anon_sym_RPAREN,
      anon_sym_LPAREN2,
      anon_sym_COMMA,
      sym_side,
  [767] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(63), 1,
      sym_math_op,
    ACTIONS(61), 9,
      anon_sym_DQUOTE,
      sym_number,
      sym_hex_color,
      sym_css_var,
      sym__ident,
      anon_sym_RPAREN,
      anon_sym_LPAREN2,
      anon_sym_COMMA,
      sym_side,
  [785] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(57), 1,
      sym_math_op,
    ACTIONS(55), 9,
      anon_sym_DQUOTE,
      sym_number,
      sym_hex_color,
      sym_css_var,
      sym__ident,
      anon_sym_RPAREN,
      anon_sym_LPAREN2,
      anon_sym_COMMA,
      sym_side,
  [803] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(89), 1,
      sym_math_op,
    ACTIONS(87), 9,
      anon_sym_DQUOTE,
      sym_number,
      sym_hex_color,
      sym_css_var,
      sym__ident,
      anon_sym_RPAREN,
      anon_sym_LPAREN2,
      anon_sym_COMMA,
      sym_side,
  [821] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(69), 1,
      sym_math_op,
    ACTIONS(67), 9,
      anon_sym_DQUOTE,
      sym_number,
      sym_hex_color,
      sym_css_var,
      sym__ident,
      anon_sym_RPAREN,
      anon_sym_LPAREN2,
      anon_sym_COMMA,
      sym_side,
  [839] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(81), 1,
      sym_math_op,
    ACTIONS(79), 9,
      anon_sym_DQUOTE,
      sym_number,
      sym_hex_color,
      sym_css_var,
      sym__ident,
      anon_sym_RPAREN,
      anon_sym_LPAREN2,
      anon_sym_COMMA,
      sym_side,
  [857] = 4,
    ACTIONS(184), 1,
      sym_comment,
    ACTIONS(186), 1,
      anon_sym_DQUOTE,
    STATE(37), 1,
      aux_sym_string_repeat1,
    ACTIONS(188), 2,
      aux_sym_string_token1,
      sym_escape,
  [871] = 4,
    ACTIONS(184), 1,
      sym_comment,
    ACTIONS(191), 1,
      anon_sym_DQUOTE,
    STATE(39), 1,
      aux_sym_string_repeat1,
    ACTIONS(193), 2,
      aux_sym_string_token1,
      sym_escape,
  [885] = 4,
    ACTIONS(184), 1,
      sym_comment,
    ACTIONS(195), 1,
      anon_sym_DQUOTE,
    STATE(37), 1,
      aux_sym_string_repeat1,
    ACTIONS(197), 2,
      aux_sym_string_token1,
      sym_escape,
  [899] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(199), 1,
      sym__ident,
    ACTIONS(201), 1,
      sym_id,
    ACTIONS(203), 1,
      anon_sym_PIPE,
    ACTIONS(205), 1,
      anon_sym_DASH,
  [915] = 4,
    ACTIONS(184), 1,
      sym_comment,
    ACTIONS(207), 1,
      anon_sym_DQUOTE,
    STATE(42), 1,
      aux_sym_string_repeat1,
    ACTIONS(209), 2,
      aux_sym_string_token1,
      sym_escape,
  [929] = 4,
    ACTIONS(184), 1,
      sym_comment,
    ACTIONS(211), 1,
      anon_sym_DQUOTE,
    STATE(37), 1,
      aux_sym_string_repeat1,
    ACTIONS(197), 2,
      aux_sym_string_token1,
      sym_escape,
  [943] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(213), 1,
      sym_id,
    ACTIONS(215), 1,
      sym_define_op,
    ACTIONS(217), 1,
      anon_sym_PIPE,
  [956] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(219), 1,
      sym_id,
    ACTIONS(221), 1,
      anon_sym_PIPE,
  [966] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(223), 1,
      sym_id,
    ACTIONS(225), 1,
      anon_sym_PIPE,
  [976] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(227), 1,
      anon_sym_PIPE,
  [983] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(229), 1,
      ts_builtin_sym_end,
  [990] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(231), 1,
      anon_sym_PIPE,
  [997] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(233), 1,
      anon_sym_PIPE,
  [1004] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(235), 1,
      sym__ident,
  [1011] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(221), 1,
      anon_sym_PIPE,
  [1018] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(237), 1,
      sym_assign_op,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(5)] = 0,
  [SMALL_STATE(6)] = 29,
  [SMALL_STATE(7)] = 58,
  [SMALL_STATE(8)] = 84,
  [SMALL_STATE(9)] = 110,
  [SMALL_STATE(10)] = 136,
  [SMALL_STATE(11)] = 162,
  [SMALL_STATE(12)] = 188,
  [SMALL_STATE(13)] = 214,
  [SMALL_STATE(14)] = 240,
  [SMALL_STATE(15)] = 266,
  [SMALL_STATE(16)] = 292,
  [SMALL_STATE(17)] = 318,
  [SMALL_STATE(18)] = 344,
  [SMALL_STATE(19)] = 370,
  [SMALL_STATE(20)] = 396,
  [SMALL_STATE(21)] = 422,
  [SMALL_STATE(22)] = 456,
  [SMALL_STATE(23)] = 490,
  [SMALL_STATE(24)] = 524,
  [SMALL_STATE(25)] = 558,
  [SMALL_STATE(26)] = 592,
  [SMALL_STATE(27)] = 626,
  [SMALL_STATE(28)] = 660,
  [SMALL_STATE(29)] = 694,
  [SMALL_STATE(30)] = 728,
  [SMALL_STATE(31)] = 749,
  [SMALL_STATE(32)] = 767,
  [SMALL_STATE(33)] = 785,
  [SMALL_STATE(34)] = 803,
  [SMALL_STATE(35)] = 821,
  [SMALL_STATE(36)] = 839,
  [SMALL_STATE(37)] = 857,
  [SMALL_STATE(38)] = 871,
  [SMALL_STATE(39)] = 885,
  [SMALL_STATE(40)] = 899,
  [SMALL_STATE(41)] = 915,
  [SMALL_STATE(42)] = 929,
  [SMALL_STATE(43)] = 943,
  [SMALL_STATE(44)] = 956,
  [SMALL_STATE(45)] = 966,
  [SMALL_STATE(46)] = 976,
  [SMALL_STATE(47)] = 983,
  [SMALL_STATE(48)] = 990,
  [SMALL_STATE(49)] = 997,
  [SMALL_STATE(50)] = 1004,
  [SMALL_STATE(51)] = 1011,
  [SMALL_STATE(52)] = 1018,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [27] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(38),
  [30] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [33] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [36] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [39] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(40),
  [42] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_value_ident, 1, 0, 1),
  [47] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_value_ident, 1, 0, 1),
  [49] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 3, 0, 4),
  [57] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call, 3, 0, 4),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_params, 2, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 4, 0, 4),
  [63] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call, 4, 0, 4),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_params, 3, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 2, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property, 2, 0, 2),
  [73] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_property, 2, 0, 2),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment, 2, 0, 3),
  [77] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_assignment, 2, 0, 3),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_bars, 2, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type_bars, 2, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_group, 2, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_group, 2, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment, 3, 0, 3),
  [93] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_assignment, 3, 0, 3),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_bars, 3, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type_bars, 3, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_bars, 5, 0, 5),
  [101] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type_bars, 5, 0, 5),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_group, 3, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_group, 3, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_bars, 4, 0, 5),
  [109] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type_bars, 4, 0, 5),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_bars, 3, 0, 5),
  [113] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type_bars, 3, 0, 5),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_bars, 6, 0, 5),
  [117] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type_bars, 6, 0, 5),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_bars, 4, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type_bars, 4, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [133] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [139] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [145] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [149] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_params_repeat1, 2, 0, 0), SHIFT_REPEAT(41),
  [152] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_params_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [155] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_params_repeat1, 2, 0, 0), SHIFT_REPEAT(30),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_params_repeat1, 2, 0, 0),
  [160] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_params_repeat1, 2, 0, 0), SHIFT_REPEAT(28),
  [163] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_params_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [170] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [178] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [184] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [186] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0),
  [188] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(37),
  [191] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [193] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [195] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [197] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [207] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [209] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [211] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [229] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_lini(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
