/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 55
#define LARGE_STATE_COUNT 5
#define SYMBOL_COUNT 45
#define ALIAS_COUNT 2
#define TOKEN_COUNT 29
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 1
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 6
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_comment = 1,
  anon_sym_DQUOTE = 2,
  aux_sym_string_token1 = 3,
  sym_escape = 4,
  sym_number = 5,
  sym_hex_color = 6,
  sym_css_var = 7,
  sym__ident = 8,
  sym_id = 9,
  sym_define_op = 10,
  anon_sym_PIPE = 11,
  anon_sym_DASH = 12,
  anon_sym_COLON = 13,
  sym_assign_op = 14,
  anon_sym_LPAREN = 15,
  anon_sym_RPAREN = 16,
  anon_sym_LPAREN2 = 17,
  anon_sym_COMMA = 18,
  sym_math_op = 19,
  sym_class = 20,
  sym_side = 21,
  sym_link_op = 22,
  sym_fanout = 23,
  anon_sym_LBRACE = 24,
  anon_sym_RBRACE = 25,
  anon_sym_LBRACK = 26,
  anon_sym_RBRACK = 27,
  anon_sym_SEMI = 28,
  sym_source_file = 29,
  sym__item = 30,
  sym_string = 31,
  sym_type_bars = 32,
  sym_property = 33,
  sym_var_decl = 34,
  sym_params = 35,
  sym_assignment = 36,
  sym_call = 37,
  sym_group = 38,
  sym__expr_item = 39,
  sym_value_ident = 40,
  sym__punct = 41,
  aux_sym_source_file_repeat1 = 42,
  aux_sym_string_repeat1 = 43,
  aux_sym_params_repeat1 = 44,
  alias_sym_call_name = 45,
  alias_sym_type = 46,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_comment] = "comment",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_token1] = "string_token1",
  [sym_escape] = "escape",
  [sym_number] = "number",
  [sym_hex_color] = "hex_color",
  [sym_css_var] = "css_var",
  [sym__ident] = "_ident",
  [sym_id] = "id",
  [sym_define_op] = "define_op",
  [anon_sym_PIPE] = "|",
  [anon_sym_DASH] = "-",
  [anon_sym_COLON] = ":",
  [sym_assign_op] = "assign_op",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LPAREN2] = "(",
  [anon_sym_COMMA] = ",",
  [sym_math_op] = "math_op",
  [sym_class] = "class",
  [sym_side] = "side",
  [sym_link_op] = "link_op",
  [sym_fanout] = "fanout",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_SEMI] = ";",
  [sym_source_file] = "source_file",
  [sym__item] = "_item",
  [sym_string] = "string",
  [sym_type_bars] = "type_bars",
  [sym_property] = "property",
  [sym_var_decl] = "var_decl",
  [sym_params] = "params",
  [sym_assignment] = "assignment",
  [sym_call] = "call",
  [sym_group] = "group",
  [sym__expr_item] = "_expr_item",
  [sym_value_ident] = "value_ident",
  [sym__punct] = "_punct",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
  [aux_sym_params_repeat1] = "params_repeat1",
  [alias_sym_call_name] = "call_name",
  [alias_sym_type] = "type",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_comment] = sym_comment,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [sym_escape] = sym_escape,
  [sym_number] = sym_number,
  [sym_hex_color] = sym_hex_color,
  [sym_css_var] = sym_css_var,
  [sym__ident] = sym__ident,
  [sym_id] = sym_id,
  [sym_define_op] = sym_define_op,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_COLON] = anon_sym_COLON,
  [sym_assign_op] = sym_assign_op,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LPAREN2] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [sym_math_op] = sym_math_op,
  [sym_class] = sym_class,
  [sym_side] = sym_side,
  [sym_link_op] = sym_link_op,
  [sym_fanout] = sym_fanout,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [sym_source_file] = sym_source_file,
  [sym__item] = sym__item,
  [sym_string] = sym_string,
  [sym_type_bars] = sym_type_bars,
  [sym_property] = sym_property,
  [sym_var_decl] = sym_var_decl,
  [sym_params] = sym_params,
  [sym_assignment] = sym_assignment,
  [sym_call] = sym_call,
  [sym_group] = sym_group,
  [sym__expr_item] = sym__expr_item,
  [sym_value_ident] = sym_value_ident,
  [sym__punct] = sym__punct,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
  [aux_sym_params_repeat1] = aux_sym_params_repeat1,
  [alias_sym_call_name] = alias_sym_call_name,
  [alias_sym_type] = alias_sym_type,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_escape] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_hex_color] = {
    .visible = true,
    .named = true,
  },
  [sym_css_var] = {
    .visible = true,
    .named = true,
  },
  [sym__ident] = {
    .visible = false,
    .named = true,
  },
  [sym_id] = {
    .visible = true,
    .named = true,
  },
  [sym_define_op] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_assign_op] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN2] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [sym_math_op] = {
    .visible = true,
    .named = true,
  },
  [sym_class] = {
    .visible = true,
    .named = true,
  },
  [sym_side] = {
    .visible = true,
    .named = true,
  },
  [sym_link_op] = {
    .visible = true,
    .named = true,
  },
  [sym_fanout] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__item] = {
    .visible = false,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_type_bars] = {
    .visible = true,
    .named = true,
  },
  [sym_property] = {
    .visible = true,
    .named = true,
  },
  [sym_var_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_params] = {
    .visible = true,
    .named = true,
  },
  [sym_assignment] = {
    .visible = true,
    .named = true,
  },
  [sym_call] = {
    .visible = true,
    .named = true,
  },
  [sym_group] = {
    .visible = true,
    .named = true,
  },
  [sym__expr_item] = {
    .visible = false,
    .named = true,
  },
  [sym_value_ident] = {
    .visible = true,
    .named = true,
  },
  [sym__punct] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_params_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_call_name] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_type] = {
    .visible = true,
    .named = true,
  },
};

enum ts_field_identifiers {
  field_name = 1,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_name] = "name",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [2] = {.index = 0, .length = 1},
  [3] = {.index = 0, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [0] = sym_value_ident,
  },
  [2] = {
    [0] = sym_property,
  },
  [3] = {
    [0] = sym_value_ident,
  },
  [4] = {
    [0] = alias_sym_call_name,
  },
  [5] = {
    [1] = alias_sym_type,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 24,
  [31] = 28,
  [32] = 32,
  [33] = 8,
  [34] = 34,
  [35] = 35,
  [36] = 18,
  [37] = 22,
  [38] = 14,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 41,
  [43] = 43,
  [44] = 39,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
};

static const TSCharacterRange sym_math_op_character_set_1[] = {
  {'!', '!'}, {'%', '%'}, {'*', '+'}, {'-', '-'}, {'/', '/'}, {':', ':'}, {'<', '?'}, {'^', '^'},
  {'~', '~'},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(26);
      ADVANCE_MAP(
        '"', 30,
        '#', 17,
        '&', 73,
        '(', 56,
        ')', 57,
        '+', 6,
        ',', 59,
        '-', 53,
        '.', 13,
        '/', 8,
        ':', 54,
        ';', 78,
        '=', 55,
        '[', 76,
        '\\', 11,
        ']', 77,
        'o', 43,
        '{', 74,
        '|', 51,
        '}', 75,
        '~', 72,
        '*', 7,
        '<', 7,
        '>', 7,
      );
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(23);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(35);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(1);
      if (lookahead == '"') ADVANCE(30);
      if (lookahead == '/') ADVANCE(32);
      if (lookahead == '\\') ADVANCE(11);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(31);
      if (lookahead != 0) ADVANCE(33);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        '"', 30,
        '#', 17,
        '(', 56,
        ')', 57,
        '+', 61,
        ',', 59,
        '-', 60,
        '.', 12,
        '/', 62,
        ':', 64,
      );
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(4);
      if (lookahead == '!' ||
          lookahead == '%' ||
          lookahead == '*' ||
          ('<' <= lookahead && lookahead <= '?') ||
          lookahead == '^' ||
          lookahead == '~') ADVANCE(63);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(35);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 3:
      ADVANCE_MAP(
        '"', 30,
        '#', 17,
        '(', 58,
        ')', 57,
        '+', 61,
        ',', 59,
        '-', 60,
        '.', 12,
        '/', 62,
        ':', 64,
        '|', 50,
      );
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(3);
      if (lookahead == '!' ||
          lookahead == '%' ||
          lookahead == '*' ||
          ('<' <= lookahead && lookahead <= '?') ||
          lookahead == '^' ||
          lookahead == '~') ADVANCE(63);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(35);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 4:
      ADVANCE_MAP(
        '"', 30,
        '#', 17,
        '(', 58,
        ')', 57,
        '+', 61,
        ',', 59,
        '-', 60,
        '.', 12,
        '/', 62,
        ':', 64,
      );
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(4);
      if (lookahead == '!' ||
          lookahead == '%' ||
          lookahead == '*' ||
          ('<' <= lookahead && lookahead <= '?') ||
          lookahead == '^' ||
          lookahead == '~') ADVANCE(63);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(35);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 5:
      if (lookahead == '#') ADVANCE(21);
      if (lookahead == '-') ADVANCE(52);
      if (lookahead == '/') ADVANCE(8);
      if (lookahead == ':') ADVANCE(9);
      if (lookahead == '|') ADVANCE(50);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(5);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 6:
      ADVANCE_MAP(
        '-', 71,
        '.', 12,
        '|', 10,
        '~', 72,
        '*', 7,
        '+', 7,
        '<', 7,
        '>', 7,
        'o', 7,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(35);
      END_STATE();
    case 7:
      if (lookahead == '-') ADVANCE(71);
      if (lookahead == '|') ADVANCE(10);
      if (lookahead == '~') ADVANCE(72);
      if (lookahead == '*' ||
          lookahead == '+' ||
          lookahead == '<' ||
          lookahead == '>' ||
          lookahead == 'o') ADVANCE(7);
      END_STATE();
    case 8:
      if (lookahead == '/') ADVANCE(29);
      END_STATE();
    case 9:
      if (lookahead == ':') ADVANCE(49);
      END_STATE();
    case 10:
      if (lookahead == '|') ADVANCE(72);
      END_STATE();
    case 11:
      if (lookahead == '"' ||
          lookahead == '\\' ||
          lookahead == 'n' ||
          lookahead == 't') ADVANCE(34);
      END_STATE();
    case 12:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(36);
      END_STATE();
    case 13:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(36);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 14:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(38);
      END_STATE();
    case 15:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(37);
      END_STATE();
    case 16:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(14);
      END_STATE();
    case 17:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(16);
      END_STATE();
    case 18:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(40);
      END_STATE();
    case 19:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 20:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(67);
      END_STATE();
    case 21:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(48);
      END_STATE();
    case 22:
      if (eof) ADVANCE(26);
      ADVANCE_MAP(
        '"', 30,
        '#', 17,
        '&', 73,
        '(', 56,
        '+', 6,
        ',', 59,
        '-', 70,
        '.', 13,
        '/', 8,
        ':', 54,
        ';', 78,
        '=', 55,
        '[', 76,
        ']', 77,
        'o', 43,
        '{', 74,
        '|', 51,
        '}', 75,
        '~', 72,
        '*', 7,
        '<', 7,
        '>', 7,
      );
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(25);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(35);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 23:
      if (eof) ADVANCE(26);
      ADVANCE_MAP(
        '"', 30,
        '#', 17,
        '&', 73,
        '(', 58,
        ')', 57,
        '+', 6,
        ',', 59,
        '-', 53,
        '.', 13,
        '/', 8,
        ':', 20,
        ';', 78,
        '=', 55,
        '[', 76,
        '\\', 11,
        ']', 77,
        'o', 43,
        '{', 74,
        '|', 51,
        '}', 75,
        '~', 72,
        '*', 7,
        '<', 7,
        '>', 7,
      );
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(23);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(35);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 24:
      if (eof) ADVANCE(26);
      ADVANCE_MAP(
        '"', 30,
        '#', 17,
        '&', 73,
        '(', 58,
        '+', 6,
        ',', 59,
        '-', 70,
        '.', 13,
        '/', 8,
        ':', 54,
        ';', 78,
        '=', 55,
        '[', 76,
        ']', 77,
        'o', 43,
        '{', 74,
        '|', 51,
        '}', 75,
        '~', 72,
        '*', 7,
        '<', 7,
        '>', 7,
      );
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(25);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(35);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 25:
      if (eof) ADVANCE(26);
      ADVANCE_MAP(
        '"', 30,
        '#', 17,
        '&', 73,
        '(', 58,
        '+', 6,
        ',', 59,
        '-', 70,
        '.', 13,
        '/', 8,
        ':', 20,
        ';', 78,
        '=', 55,
        '[', 76,
        ']', 77,
        'o', 43,
        '{', 74,
        '|', 51,
        '}', 75,
        '~', 72,
        '*', 7,
        '<', 7,
        '>', 7,
      );
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(25);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(35);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '"' ||
          lookahead == '\\') ADVANCE(29);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_comment);
      if (set_contains(sym_math_op_character_set_1, 9, lookahead)) ADVANCE(28);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(29);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(29);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '/') ADVANCE(32);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(31);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(33);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '/') ADVANCE(27);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(33);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(33);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_escape);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(12);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(35);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(36);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_hex_color);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_hex_color);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(39);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_hex_color);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(18);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_hex_color);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(15);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_css_var);
      if (lookahead == 'o') ADVANCE(41);
      if (lookahead == '*' ||
          lookahead == '+' ||
          lookahead == '<' ||
          lookahead == '>') ADVANCE(72);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_css_var);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym__ident);
      if (lookahead == '-') ADVANCE(45);
      if (lookahead == 'o') ADVANCE(43);
      if (lookahead == '|') ADVANCE(10);
      if (lookahead == '~') ADVANCE(72);
      if (lookahead == '*' ||
          lookahead == '+' ||
          lookahead == '<' ||
          lookahead == '>') ADVANCE(7);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym__ident);
      if (lookahead == '-') ADVANCE(46);
      if (lookahead == 'o') ADVANCE(46);
      if (lookahead == '*' ||
          lookahead == '+' ||
          lookahead == '<' ||
          lookahead == '>') ADVANCE(72);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym__ident);
      if (lookahead == '-') ADVANCE(44);
      if (lookahead == 'o') ADVANCE(46);
      if (lookahead == '*' ||
          lookahead == '+' ||
          lookahead == '<' ||
          lookahead == '>') ADVANCE(72);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym__ident);
      if (lookahead == 'o') ADVANCE(46);
      if (lookahead == '*' ||
          lookahead == '+' ||
          lookahead == '<' ||
          lookahead == '>') ADVANCE(72);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym__ident);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_id);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(48);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_define_op);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_PIPE);
      if (lookahead == '|') ADVANCE(72);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (lookahead == '-') ADVANCE(68);
      if (lookahead == '.') ADVANCE(12);
      if (lookahead == '*' ||
          lookahead == '+' ||
          lookahead == '<' ||
          lookahead == '>' ||
          lookahead == 'o') ADVANCE(72);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(35);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_COLON);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(67);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_assign_op);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_LPAREN2);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_math_op);
      if (lookahead == '-') ADVANCE(65);
      if (lookahead == '.') ADVANCE(12);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(35);
      if (lookahead == '!' ||
          lookahead == '%' ||
          lookahead == '*' ||
          lookahead == '+' ||
          ('/' <= lookahead && lookahead <= ':') ||
          ('<' <= lookahead && lookahead <= '?') ||
          lookahead == '^' ||
          lookahead == '~') ADVANCE(63);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_math_op);
      if (lookahead == '.') ADVANCE(12);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(35);
      if (lookahead == '!' ||
          lookahead == '%' ||
          lookahead == '*' ||
          lookahead == '+' ||
          ('-' <= lookahead && lookahead <= ':') ||
          ('<' <= lookahead && lookahead <= '?') ||
          lookahead == '^' ||
          lookahead == '~') ADVANCE(63);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_math_op);
      if (lookahead == '/') ADVANCE(28);
      if (set_contains(sym_math_op_character_set_1, 9, lookahead)) ADVANCE(63);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_math_op);
      if (set_contains(sym_math_op_character_set_1, 9, lookahead)) ADVANCE(63);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_math_op);
      if (set_contains(sym_math_op_character_set_1, 9, lookahead)) ADVANCE(63);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(67);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_math_op);
      if (set_contains(sym_math_op_character_set_1, 9, lookahead)) ADVANCE(63);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_class);
      if (lookahead == '.') ADVANCE(19);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_side);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(67);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_link_op);
      if (lookahead == '-') ADVANCE(72);
      if (lookahead == 'o') ADVANCE(41);
      if (lookahead == '*' ||
          lookahead == '+' ||
          lookahead == '<' ||
          lookahead == '>') ADVANCE(72);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_link_op);
      if (lookahead == '-') ADVANCE(72);
      if (lookahead == '*' ||
          lookahead == '+' ||
          lookahead == '<' ||
          lookahead == '>' ||
          lookahead == 'o') ADVANCE(72);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_link_op);
      if (lookahead == '-') ADVANCE(68);
      if (lookahead == '.') ADVANCE(12);
      if (lookahead == '*' ||
          lookahead == '+' ||
          lookahead == '<' ||
          lookahead == '>' ||
          lookahead == 'o') ADVANCE(72);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(35);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_link_op);
      if (lookahead == '-') ADVANCE(69);
      if (lookahead == '*' ||
          lookahead == '+' ||
          lookahead == '<' ||
          lookahead == '>' ||
          lookahead == 'o') ADVANCE(72);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_link_op);
      if (lookahead == '*' ||
          lookahead == '+' ||
          lookahead == '<' ||
          lookahead == '>' ||
          lookahead == 'o') ADVANCE(72);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_fanout);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 24},
  [2] = {.lex_state = 24},
  [3] = {.lex_state = 24},
  [4] = {.lex_state = 22},
  [5] = {.lex_state = 24},
  [6] = {.lex_state = 24},
  [7] = {.lex_state = 24},
  [8] = {.lex_state = 24},
  [9] = {.lex_state = 24},
  [10] = {.lex_state = 24},
  [11] = {.lex_state = 24},
  [12] = {.lex_state = 24},
  [13] = {.lex_state = 24},
  [14] = {.lex_state = 24},
  [15] = {.lex_state = 24},
  [16] = {.lex_state = 24},
  [17] = {.lex_state = 24},
  [18] = {.lex_state = 24},
  [19] = {.lex_state = 24},
  [20] = {.lex_state = 24},
  [21] = {.lex_state = 24},
  [22] = {.lex_state = 24},
  [23] = {.lex_state = 3},
  [24] = {.lex_state = 3},
  [25] = {.lex_state = 3},
  [26] = {.lex_state = 3},
  [27] = {.lex_state = 3},
  [28] = {.lex_state = 3},
  [29] = {.lex_state = 3},
  [30] = {.lex_state = 3},
  [31] = {.lex_state = 3},
  [32] = {.lex_state = 2},
  [33] = {.lex_state = 3},
  [34] = {.lex_state = 3},
  [35] = {.lex_state = 3},
  [36] = {.lex_state = 3},
  [37] = {.lex_state = 3},
  [38] = {.lex_state = 3},
  [39] = {.lex_state = 1},
  [40] = {.lex_state = 1},
  [41] = {.lex_state = 1},
  [42] = {.lex_state = 1},
  [43] = {.lex_state = 5},
  [44] = {.lex_state = 1},
  [45] = {.lex_state = 5},
  [46] = {.lex_state = 5},
  [47] = {.lex_state = 5},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 3},
  [50] = {.lex_state = 3},
  [51] = {.lex_state = 3},
  [52] = {.lex_state = 3},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 3},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym_escape] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_hex_color] = ACTIONS(1),
    [sym_css_var] = ACTIONS(1),
    [sym__ident] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [sym_assign_op] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LPAREN2] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [sym_class] = ACTIONS(1),
    [sym_side] = ACTIONS(1),
    [sym_link_op] = ACTIONS(1),
    [sym_fanout] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(48),
    [sym__item] = STATE(2),
    [sym_string] = STATE(2),
    [sym_type_bars] = STATE(2),
    [sym_property] = STATE(2),
    [sym_var_decl] = STATE(2),
    [sym_assignment] = STATE(2),
    [sym_call] = STATE(2),
    [sym_group] = STATE(2),
    [sym_value_ident] = STATE(2),
    [sym__punct] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_comment] = ACTIONS(3),
    [anon_sym_DQUOTE] = ACTIONS(7),
    [sym_number] = ACTIONS(9),
    [sym_hex_color] = ACTIONS(9),
    [sym_css_var] = ACTIONS(11),
    [sym__ident] = ACTIONS(13),
    [anon_sym_PIPE] = ACTIONS(15),
    [anon_sym_LPAREN2] = ACTIONS(17),
    [anon_sym_COMMA] = ACTIONS(9),
    [sym_class] = ACTIONS(9),
    [sym_side] = ACTIONS(9),
    [sym_link_op] = ACTIONS(19),
    [sym_fanout] = ACTIONS(9),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_RBRACE] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(9),
    [anon_sym_RBRACK] = ACTIONS(9),
    [anon_sym_SEMI] = ACTIONS(9),
  },
  [STATE(2)] = {
    [sym__item] = STATE(3),
    [sym_string] = STATE(3),
    [sym_type_bars] = STATE(3),
    [sym_property] = STATE(3),
    [sym_var_decl] = STATE(3),
    [sym_assignment] = STATE(3),
    [sym_call] = STATE(3),
    [sym_group] = STATE(3),
    [sym_value_ident] = STATE(3),
    [sym__punct] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(21),
    [sym_comment] = ACTIONS(3),
    [anon_sym_DQUOTE] = ACTIONS(7),
    [sym_number] = ACTIONS(23),
    [sym_hex_color] = ACTIONS(23),
    [sym_css_var] = ACTIONS(11),
    [sym__ident] = ACTIONS(13),
    [anon_sym_PIPE] = ACTIONS(15),
    [anon_sym_LPAREN2] = ACTIONS(17),
    [anon_sym_COMMA] = ACTIONS(23),
    [sym_class] = ACTIONS(23),
    [sym_side] = ACTIONS(23),
    [sym_link_op] = ACTIONS(25),
    [sym_fanout] = ACTIONS(23),
    [anon_sym_LBRACE] = ACTIONS(23),
    [anon_sym_RBRACE] = ACTIONS(23),
    [anon_sym_LBRACK] = ACTIONS(23),
    [anon_sym_RBRACK] = ACTIONS(23),
    [anon_sym_SEMI] = ACTIONS(23),
  },
  [STATE(3)] = {
    [sym__item] = STATE(3),
    [sym_string] = STATE(3),
    [sym_type_bars] = STATE(3),
    [sym_property] = STATE(3),
    [sym_var_decl] = STATE(3),
    [sym_assignment] = STATE(3),
    [sym_call] = STATE(3),
    [sym_group] = STATE(3),
    [sym_value_ident] = STATE(3),
    [sym__punct] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(27),
    [sym_comment] = ACTIONS(3),
    [anon_sym_DQUOTE] = ACTIONS(29),
    [sym_number] = ACTIONS(32),
    [sym_hex_color] = ACTIONS(32),
    [sym_css_var] = ACTIONS(35),
    [sym__ident] = ACTIONS(38),
    [anon_sym_PIPE] = ACTIONS(41),
    [anon_sym_LPAREN2] = ACTIONS(44),
    [anon_sym_COMMA] = ACTIONS(32),
    [sym_class] = ACTIONS(32),
    [sym_side] = ACTIONS(32),
    [sym_link_op] = ACTIONS(47),
    [sym_fanout] = ACTIONS(32),
    [anon_sym_LBRACE] = ACTIONS(32),
    [anon_sym_RBRACE] = ACTIONS(32),
    [anon_sym_LBRACK] = ACTIONS(32),
    [anon_sym_RBRACK] = ACTIONS(32),
    [anon_sym_SEMI] = ACTIONS(32),
  },
  [STATE(4)] = {
    [sym_params] = STATE(53),
    [ts_builtin_sym_end] = ACTIONS(50),
    [sym_comment] = ACTIONS(3),
    [anon_sym_DQUOTE] = ACTIONS(50),
    [sym_number] = ACTIONS(50),
    [sym_hex_color] = ACTIONS(50),
    [sym_css_var] = ACTIONS(52),
    [sym__ident] = ACTIONS(52),
    [anon_sym_PIPE] = ACTIONS(52),
    [anon_sym_COLON] = ACTIONS(54),
    [sym_assign_op] = ACTIONS(56),
    [anon_sym_LPAREN] = ACTIONS(58),
    [anon_sym_LPAREN2] = ACTIONS(52),
    [anon_sym_COMMA] = ACTIONS(50),
    [sym_class] = ACTIONS(50),
    [sym_side] = ACTIONS(50),
    [sym_link_op] = ACTIONS(52),
    [sym_fanout] = ACTIONS(50),
    [anon_sym_LBRACE] = ACTIONS(50),
    [anon_sym_RBRACE] = ACTIONS(50),
    [anon_sym_LBRACK] = ACTIONS(50),
    [anon_sym_RBRACK] = ACTIONS(50),
    [anon_sym_SEMI] = ACTIONS(50),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(64), 1,
      anon_sym_COLON,
    ACTIONS(62), 4,
      sym_css_var,
      sym__ident,
      anon_sym_PIPE,
      sym_link_op,
    ACTIONS(60), 14,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
      sym_number,
      sym_hex_color,
      anon_sym_LPAREN2,
      anon_sym_COMMA,
      sym_class,
      sym_side,
      sym_fanout,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_SEMI,
  [29] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(70), 1,
      sym_assign_op,
    ACTIONS(68), 4,
      sym_css_var,
      sym__ident,
      anon_sym_PIPE,
      sym_link_op,
    ACTIONS(66), 14,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
      sym_number,
      sym_hex_color,
      anon_sym_LPAREN2,
      anon_sym_COMMA,
      sym_class,
      sym_side,
      sym_fanout,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_SEMI,
  [58] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(76), 1,
      sym_assign_op,
    ACTIONS(74), 4,
      sym_css_var,
      sym__ident,
      anon_sym_PIPE,
      sym_link_op,
    ACTIONS(72), 14,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
      sym_number,
      sym_hex_color,
      anon_sym_LPAREN2,
      anon_sym_COMMA,
      sym_class,
      sym_side,
      sym_fanout,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_SEMI,
  [87] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(80), 4,
      sym_css_var,
      sym__ident,
      anon_sym_PIPE,
      sym_link_op,
    ACTIONS(78), 14,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
      sym_number,
      sym_hex_color,
      anon_sym_LPAREN2,
      anon_sym_COMMA,
      sym_class,
      sym_side,
      sym_fanout,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_SEMI,
  [113] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(84), 4,
      sym_css_var,
      sym__ident,
      anon_sym_PIPE,
      sym_link_op,
    ACTIONS(82), 14,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
      sym_number,
      sym_hex_color,
      anon_sym_LPAREN2,
      anon_sym_COMMA,
      sym_class,
      sym_side,
      sym_fanout,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_SEMI,
  [139] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(88), 4,
      sym_css_var,
      sym__ident,
      anon_sym_PIPE,
      sym_link_op,
    ACTIONS(86), 14,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
      sym_number,
      sym_hex_color,
      anon_sym_LPAREN2,
      anon_sym_COMMA,
      sym_class,
      sym_side,
      sym_fanout,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_SEMI,
  [165] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(92), 4,
      sym_css_var,
      sym__ident,
      anon_sym_PIPE,
      sym_link_op,
    ACTIONS(90), 14,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
      sym_number,
      sym_hex_color,
      anon_sym_LPAREN2,
      anon_sym_COMMA,
      sym_class,
      sym_side,
      sym_fanout,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_SEMI,
  [191] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(96), 4,
      sym_css_var,
      sym__ident,
      anon_sym_PIPE,
      sym_link_op,
    ACTIONS(94), 14,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
      sym_number,
      sym_hex_color,
      anon_sym_LPAREN2,
      anon_sym_COMMA,
      sym_class,
      sym_side,
      sym_fanout,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_SEMI,
  [217] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(100), 4,
      sym_css_var,
      sym__ident,
      anon_sym_PIPE,
      sym_link_op,
    ACTIONS(98), 14,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
      sym_number,
      sym_hex_color,
      anon_sym_LPAREN2,
      anon_sym_COMMA,
      sym_class,
      sym_side,
      sym_fanout,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_SEMI,
  [243] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(104), 4,
      sym_css_var,
      sym__ident,
      anon_sym_PIPE,
      sym_link_op,
    ACTIONS(102), 14,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
      sym_number,
      sym_hex_color,
      anon_sym_LPAREN2,
      anon_sym_COMMA,
      sym_class,
      sym_side,
      sym_fanout,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_SEMI,
  [269] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(108), 4,
      sym_css_var,
      sym__ident,
      anon_sym_PIPE,
      sym_link_op,
    ACTIONS(106), 14,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
      sym_number,
      sym_hex_color,
      anon_sym_LPAREN2,
      anon_sym_COMMA,
      sym_class,
      sym_side,
      sym_fanout,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_SEMI,
  [295] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(112), 4,
      sym_css_var,
      sym__ident,
      anon_sym_PIPE,
      sym_link_op,
    ACTIONS(110), 14,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
      sym_number,
      sym_hex_color,
      anon_sym_LPAREN2,
      anon_sym_COMMA,
      sym_class,
      sym_side,
      sym_fanout,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_SEMI,
  [321] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(116), 4,
      sym_css_var,
      sym__ident,
      anon_sym_PIPE,
      sym_link_op,
    ACTIONS(114), 14,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
      sym_number,
      sym_hex_color,
      anon_sym_LPAREN2,
      anon_sym_COMMA,
      sym_class,
      sym_side,
      sym_fanout,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_SEMI,
  [347] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(120), 4,
      sym_css_var,
      sym__ident,
      anon_sym_PIPE,
      sym_link_op,
    ACTIONS(118), 14,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
      sym_number,
      sym_hex_color,
      anon_sym_LPAREN2,
      anon_sym_COMMA,
      sym_class,
      sym_side,
      sym_fanout,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_SEMI,
  [373] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(124), 4,
      sym_css_var,
      sym__ident,
      anon_sym_PIPE,
      sym_link_op,
    ACTIONS(122), 14,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
      sym_number,
      sym_hex_color,
      anon_sym_LPAREN2,
      anon_sym_COMMA,
      sym_class,
      sym_side,
      sym_fanout,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_SEMI,
  [399] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(128), 4,
      sym_css_var,
      sym__ident,
      anon_sym_PIPE,
      sym_link_op,
    ACTIONS(126), 14,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
      sym_number,
      sym_hex_color,
      anon_sym_LPAREN2,
      anon_sym_COMMA,
      sym_class,
      sym_side,
      sym_fanout,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_SEMI,
  [425] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(132), 4,
      sym_css_var,
      sym__ident,
      anon_sym_PIPE,
      sym_link_op,
    ACTIONS(130), 14,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
      sym_number,
      sym_hex_color,
      anon_sym_LPAREN2,
      anon_sym_COMMA,
      sym_class,
      sym_side,
      sym_fanout,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_SEMI,
  [451] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(136), 4,
      sym_css_var,
      sym__ident,
      anon_sym_PIPE,
      sym_link_op,
    ACTIONS(134), 14,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
      sym_number,
      sym_hex_color,
      anon_sym_LPAREN2,
      anon_sym_COMMA,
      sym_class,
      sym_side,
      sym_fanout,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_SEMI,
  [477] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(138), 1,
      anon_sym_DQUOTE,
    ACTIONS(142), 1,
      sym__ident,
    ACTIONS(144), 1,
      anon_sym_RPAREN,
    ACTIONS(146), 1,
      anon_sym_LPAREN2,
    ACTIONS(148), 1,
      sym_math_op,
    ACTIONS(140), 5,
      sym_number,
      sym_hex_color,
      sym_css_var,
      anon_sym_COMMA,
      sym_side,
    STATE(27), 6,
      sym_string,
      sym_call,
      sym_group,
      sym__expr_item,
      sym_value_ident,
      aux_sym_params_repeat1,
  [511] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(138), 1,
      anon_sym_DQUOTE,
    ACTIONS(142), 1,
      sym__ident,
    ACTIONS(146), 1,
      anon_sym_LPAREN2,
    ACTIONS(152), 1,
      anon_sym_RPAREN,
    ACTIONS(154), 1,
      sym_math_op,
    ACTIONS(150), 5,
      sym_number,
      sym_hex_color,
      sym_css_var,
      anon_sym_COMMA,
      sym_side,
    STATE(28), 6,
      sym_string,
      sym_call,
      sym_group,
      sym__expr_item,
      sym_value_ident,
      aux_sym_params_repeat1,
  [545] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(138), 1,
      anon_sym_DQUOTE,
    ACTIONS(142), 1,
      sym__ident,
    ACTIONS(146), 1,
      anon_sym_LPAREN2,
    ACTIONS(158), 1,
      anon_sym_RPAREN,
    ACTIONS(160), 1,
      sym_math_op,
    ACTIONS(156), 5,
      sym_number,
      sym_hex_color,
      sym_css_var,
      anon_sym_COMMA,
      sym_side,
    STATE(23), 6,
      sym_string,
      sym_call,
      sym_group,
      sym__expr_item,
      sym_value_ident,
      aux_sym_params_repeat1,
  [579] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(138), 1,
      anon_sym_DQUOTE,
    ACTIONS(142), 1,
      sym__ident,
    ACTIONS(146), 1,
      anon_sym_LPAREN2,
    ACTIONS(164), 1,
      anon_sym_RPAREN,
    ACTIONS(166), 1,
      sym_math_op,
    ACTIONS(162), 5,
      sym_number,
      sym_hex_color,
      sym_css_var,
      anon_sym_COMMA,
      sym_side,
    STATE(29), 6,
      sym_string,
      sym_call,
      sym_group,
      sym__expr_item,
      sym_value_ident,
      aux_sym_params_repeat1,
  [613] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(168), 1,
      anon_sym_DQUOTE,
    ACTIONS(174), 1,
      sym__ident,
    ACTIONS(177), 1,
      anon_sym_RPAREN,
    ACTIONS(179), 1,
      anon_sym_LPAREN2,
    ACTIONS(182), 1,
      sym_math_op,
    ACTIONS(171), 5,
      sym_number,
      sym_hex_color,
      sym_css_var,
      anon_sym_COMMA,
      sym_side,
    STATE(27), 6,
      sym_string,
      sym_call,
      sym_group,
      sym__expr_item,
      sym_value_ident,
      aux_sym_params_repeat1,
  [647] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(138), 1,
      anon_sym_DQUOTE,
    ACTIONS(142), 1,
      sym__ident,
    ACTIONS(146), 1,
      anon_sym_LPAREN2,
    ACTIONS(148), 1,
      sym_math_op,
    ACTIONS(185), 1,
      anon_sym_RPAREN,
    ACTIONS(140), 5,
      sym_number,
      sym_hex_color,
      sym_css_var,
      anon_sym_COMMA,
      sym_side,
    STATE(27), 6,
      sym_string,
      sym_call,
      sym_group,
      sym__expr_item,
      sym_value_ident,
      aux_sym_params_repeat1,
  [681] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(138), 1,
      anon_sym_DQUOTE,
    ACTIONS(142), 1,
      sym__ident,
    ACTIONS(146), 1,
      anon_sym_LPAREN2,
    ACTIONS(148), 1,
      sym_math_op,
    ACTIONS(187), 1,
      anon_sym_RPAREN,
    ACTIONS(140), 5,
      sym_number,
      sym_hex_color,
      sym_css_var,
      anon_sym_COMMA,
      sym_side,
    STATE(27), 6,
      sym_string,
      sym_call,
      sym_group,
      sym__expr_item,
      sym_value_ident,
      aux_sym_params_repeat1,
  [715] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(138), 1,
      anon_sym_DQUOTE,
    ACTIONS(142), 1,
      sym__ident,
    ACTIONS(146), 1,
      anon_sym_LPAREN2,
    ACTIONS(191), 1,
      anon_sym_RPAREN,
    ACTIONS(193), 1,
      sym_math_op,
    ACTIONS(189), 5,
      sym_number,
      sym_hex_color,
      sym_css_var,
      anon_sym_COMMA,
      sym_side,
    STATE(31), 6,
      sym_string,
      sym_call,
      sym_group,
      sym__expr_item,
      sym_value_ident,
      aux_sym_params_repeat1,
  [749] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(138), 1,
      anon_sym_DQUOTE,
    ACTIONS(142), 1,
      sym__ident,
    ACTIONS(146), 1,
      anon_sym_LPAREN2,
    ACTIONS(148), 1,
      sym_math_op,
    ACTIONS(195), 1,
      anon_sym_RPAREN,
    ACTIONS(140), 5,
      sym_number,
      sym_hex_color,
      sym_css_var,
      anon_sym_COMMA,
      sym_side,
    STATE(27), 6,
      sym_string,
      sym_call,
      sym_group,
      sym__expr_item,
      sym_value_ident,
      aux_sym_params_repeat1,
  [783] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(197), 1,
      anon_sym_LPAREN,
    ACTIONS(52), 2,
      anon_sym_LPAREN2,
      sym_math_op,
    ACTIONS(50), 8,
      anon_sym_DQUOTE,
      sym_number,
      sym_hex_color,
      sym_css_var,
      sym__ident,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_side,
  [804] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(80), 1,
      sym_math_op,
    ACTIONS(78), 9,
      anon_sym_DQUOTE,
      sym_number,
      sym_hex_color,
      sym_css_var,
      sym__ident,
      anon_sym_RPAREN,
      anon_sym_LPAREN2,
      anon_sym_COMMA,
      sym_side,
  [822] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(68), 1,
      sym_math_op,
    ACTIONS(66), 9,
      anon_sym_DQUOTE,
      sym_number,
      sym_hex_color,
      sym_css_var,
      sym__ident,
      anon_sym_RPAREN,
      anon_sym_LPAREN2,
      anon_sym_COMMA,
      sym_side,
  [840] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(74), 1,
      sym_math_op,
    ACTIONS(72), 9,
      anon_sym_DQUOTE,
      sym_number,
      sym_hex_color,
      sym_css_var,
      sym__ident,
      anon_sym_RPAREN,
      anon_sym_LPAREN2,
      anon_sym_COMMA,
      sym_side,
  [858] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(120), 1,
      sym_math_op,
    ACTIONS(118), 9,
      anon_sym_DQUOTE,
      sym_number,
      sym_hex_color,
      sym_css_var,
      sym__ident,
      anon_sym_RPAREN,
      anon_sym_LPAREN2,
      anon_sym_COMMA,
      sym_side,
  [876] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(136), 1,
      sym_math_op,
    ACTIONS(134), 9,
      anon_sym_DQUOTE,
      sym_number,
      sym_hex_color,
      sym_css_var,
      sym__ident,
      anon_sym_RPAREN,
      anon_sym_LPAREN2,
      anon_sym_COMMA,
      sym_side,
  [894] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(104), 1,
      sym_math_op,
    ACTIONS(102), 9,
      anon_sym_DQUOTE,
      sym_number,
      sym_hex_color,
      sym_css_var,
      sym__ident,
      anon_sym_RPAREN,
      anon_sym_LPAREN2,
      anon_sym_COMMA,
      sym_side,
  [912] = 4,
    ACTIONS(199), 1,
      sym_comment,
    ACTIONS(201), 1,
      anon_sym_DQUOTE,
    STATE(40), 1,
      aux_sym_string_repeat1,
    ACTIONS(203), 2,
      aux_sym_string_token1,
      sym_escape,
  [926] = 4,
    ACTIONS(199), 1,
      sym_comment,
    ACTIONS(205), 1,
      anon_sym_DQUOTE,
    STATE(40), 1,
      aux_sym_string_repeat1,
    ACTIONS(207), 2,
      aux_sym_string_token1,
      sym_escape,
  [940] = 4,
    ACTIONS(199), 1,
      sym_comment,
    ACTIONS(210), 1,
      anon_sym_DQUOTE,
    STATE(39), 1,
      aux_sym_string_repeat1,
    ACTIONS(212), 2,
      aux_sym_string_token1,
      sym_escape,
  [954] = 4,
    ACTIONS(199), 1,
      sym_comment,
    ACTIONS(214), 1,
      anon_sym_DQUOTE,
    STATE(44), 1,
      aux_sym_string_repeat1,
    ACTIONS(216), 2,
      aux_sym_string_token1,
      sym_escape,
  [968] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(218), 1,
      sym__ident,
    ACTIONS(220), 1,
      sym_id,
    ACTIONS(222), 1,
      anon_sym_PIPE,
    ACTIONS(224), 1,
      anon_sym_DASH,
  [984] = 4,
    ACTIONS(199), 1,
      sym_comment,
    ACTIONS(226), 1,
      anon_sym_DQUOTE,
    STATE(40), 1,
      aux_sym_string_repeat1,
    ACTIONS(203), 2,
      aux_sym_string_token1,
      sym_escape,
  [998] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(228), 1,
      sym_id,
    ACTIONS(230), 1,
      sym_define_op,
    ACTIONS(232), 1,
      anon_sym_PIPE,
  [1011] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(234), 1,
      sym_id,
    ACTIONS(236), 1,
      anon_sym_PIPE,
  [1021] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(238), 1,
      sym_id,
    ACTIONS(240), 1,
      anon_sym_PIPE,
  [1031] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(242), 1,
      ts_builtin_sym_end,
  [1038] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(244), 1,
      anon_sym_PIPE,
  [1045] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(246), 1,
      sym__ident,
  [1052] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(236), 1,
      anon_sym_PIPE,
  [1059] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(248), 1,
      anon_sym_PIPE,
  [1066] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(250), 1,
      sym_assign_op,
  [1073] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(252), 1,
      anon_sym_PIPE,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(5)] = 0,
  [SMALL_STATE(6)] = 29,
  [SMALL_STATE(7)] = 58,
  [SMALL_STATE(8)] = 87,
  [SMALL_STATE(9)] = 113,
  [SMALL_STATE(10)] = 139,
  [SMALL_STATE(11)] = 165,
  [SMALL_STATE(12)] = 191,
  [SMALL_STATE(13)] = 217,
  [SMALL_STATE(14)] = 243,
  [SMALL_STATE(15)] = 269,
  [SMALL_STATE(16)] = 295,
  [SMALL_STATE(17)] = 321,
  [SMALL_STATE(18)] = 347,
  [SMALL_STATE(19)] = 373,
  [SMALL_STATE(20)] = 399,
  [SMALL_STATE(21)] = 425,
  [SMALL_STATE(22)] = 451,
  [SMALL_STATE(23)] = 477,
  [SMALL_STATE(24)] = 511,
  [SMALL_STATE(25)] = 545,
  [SMALL_STATE(26)] = 579,
  [SMALL_STATE(27)] = 613,
  [SMALL_STATE(28)] = 647,
  [SMALL_STATE(29)] = 681,
  [SMALL_STATE(30)] = 715,
  [SMALL_STATE(31)] = 749,
  [SMALL_STATE(32)] = 783,
  [SMALL_STATE(33)] = 804,
  [SMALL_STATE(34)] = 822,
  [SMALL_STATE(35)] = 840,
  [SMALL_STATE(36)] = 858,
  [SMALL_STATE(37)] = 876,
  [SMALL_STATE(38)] = 894,
  [SMALL_STATE(39)] = 912,
  [SMALL_STATE(40)] = 926,
  [SMALL_STATE(41)] = 940,
  [SMALL_STATE(42)] = 954,
  [SMALL_STATE(43)] = 968,
  [SMALL_STATE(44)] = 984,
  [SMALL_STATE(45)] = 998,
  [SMALL_STATE(46)] = 1011,
  [SMALL_STATE(47)] = 1021,
  [SMALL_STATE(48)] = 1031,
  [SMALL_STATE(49)] = 1038,
  [SMALL_STATE(50)] = 1045,
  [SMALL_STATE(51)] = 1052,
  [SMALL_STATE(52)] = 1059,
  [SMALL_STATE(53)] = 1066,
  [SMALL_STATE(54)] = 1073,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(41),
  [32] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [35] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [38] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [41] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(43),
  [44] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [47] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_value_ident, 1, 0, 1),
  [52] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_value_ident, 1, 0, 1),
  [54] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__item, 1, 0, 0),
  [62] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__item, 1, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 3, 0, 4),
  [68] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call, 3, 0, 4),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_params, 2, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 4, 0, 4),
  [74] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call, 4, 0, 4),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_params, 3, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_bars, 6, 0, 5),
  [84] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type_bars, 6, 0, 5),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_var_decl, 2, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_var_decl, 2, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property, 2, 0, 2),
  [92] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_property, 2, 0, 2),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment, 2, 0, 3),
  [96] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_assignment, 2, 0, 3),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_bars, 2, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type_bars, 2, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_group, 2, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_group, 2, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment, 3, 0, 3),
  [108] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_assignment, 3, 0, 3),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_bars, 3, 0, 5),
  [112] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type_bars, 3, 0, 5),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_bars, 3, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type_bars, 3, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_group, 3, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_group, 3, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_bars, 4, 0, 5),
  [124] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type_bars, 4, 0, 5),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_bars, 4, 0, 0),
  [128] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type_bars, 4, 0, 0),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_bars, 5, 0, 5),
  [132] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type_bars, 5, 0, 5),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2, 0, 0),
  [136] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 2, 0, 0),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [148] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [154] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [160] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [166] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [168] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_params_repeat1, 2, 0, 0), SHIFT_REPEAT(42),
  [171] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_params_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [174] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_params_repeat1, 2, 0, 0), SHIFT_REPEAT(32),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_params_repeat1, 2, 0, 0),
  [179] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_params_repeat1, 2, 0, 0), SHIFT_REPEAT(30),
  [182] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_params_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [193] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [199] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [201] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [203] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [205] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0),
  [207] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(40),
  [210] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [212] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [214] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [216] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [226] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [242] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_lini(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
