;; Generated by `cargo xtask gen-grammars` from the compiler's own tables — do not edit.
;; The keyword predicates are those word sets (types, properties, builders,
;; glyphs, layouts); a new row appears here on regeneration or the drift
;; test fails.

;; Comments, strings, numbers.
(comment) @comment
(string) @string
(escape) @string.escape
(number) @number
(hex_color) @constant

;; Identity bars: |type#id|.
(type_bars "|" @punctuation.bracket)
(id) @tag
(define_op) @operator

;; Built-in types (primitives + templates) vs user types.
((type) @type.builtin
  (#match? @type.builtin "^(BT|C|D|F|FB|I|J|L|LED|Q|R|SW|V|Y|alt|appliance|area|axis|badge|balloon|band|bars|bath|bed|block|box|breakline|bubble|caption|cell|centerline|chart|column|component|control|cyl|datum|diamond|dining|door|door-leaf|door-swing|dots|drawing|else|entity|feature-control|field|floorplan|footer|footnote|frame|gnd|grid|group|halo|header|hex|hidden|hole|icon|image|junction|label|line|loop|magnifier|mark|mindmap|nc|note|opamp|opt|oval|page|partition|path|pie|pin|pitch-circle|plane|poly|projection|rect|row|schematic|sequence|shoulder|sign|sketch|slant|slice|sofa|stack|stair-arrow|stair-tread|stairs|surface-finish|table|threadline|tick|title-block|topic|wall|window|window-sill|zone)$"))
(type) @type

;; Property names: ledger rows strongly, others weakly.
((property) @property
  (#match? @property "^(activation|align|along|approved|at|author|axis|bars|baseline|break|categories|cell|characteristic|clearance|color|columns|corner-radius|curve|data|date|datums|density|department|direction|document-type|draw|drawing-number|facing|fill|fit|fn|font-family|font-size|font-style|font-weight|format|gap|gap-fill|gridlines|height|hinge|hint|hole|href|justify|labels|layer|layout|legend|letter-spacing|line-spacing|marker|marker-end|marker-start|material|max-width|mirror|modifiers|multiple|number|of|on|opacity|padding|path|pattern|pin|pins|place|points|prefix|project|radius|range|reference|revision|revolve|rotate|routing|rows|samples|scale|shadow|shape|sheet|sheet-number|side|skew|span|src|status|step|steps|stroke|stroke-style|stroke-width|swing|symbol|text-decoration|text-shadow|text-transform|text-wrap|thickness|thread|ticks|title|tol|tooltip|translate|unit|value|width|zone)$"))
(property) @variable.other.member

;; CSS variables and the theme --vars.
(css_var) @variable

;; Value builders vs plain calls.
((call_name) @function.builtin
  (#match? @function.builtin "^(gradient|hatch|hsl|hsla|linear-gradient|oklch|radial-gradient|repeat|rgb|rgba)$"))
(call_name) @function

;; Enum value idents + layout names.
((value_ident) @constant.builtin
  (#match? @constant.builtin "^(flow|row|column|radial|bilateral|start|center|end|stretch|evenly|origin|rows|columns|none|auto|solid|dashed|dotted|wavy|phantom|log|linear|hover|always|orthogonal|natural|straight|contain|cover|x-axis|y-axis|px|mm|cm|m|in|over|arrow|dot|circle|diamond|datum|crow|many|one|exactly-one|zero-or-one|one-or-many|zero-or-many|bottom|left|right|top|chart|drawing|floorplan|grid|pie|schematic|sequence|stack|tree)$"))

;; Colour names.
((value_ident) @constant.builtin
  (#match? @constant.builtin "^(white|black|red|green|blue|gray|grey|crimson|orange|yellow|gold|silver|navy|teal|purple|pink|brown|cyan|magenta|lime|maroon|olive|cornflowerblue|currentColor|transparent)$"))

;; Classes, sides, operators, punctuation.
(class) @attribute
(side) @constant.builtin
(link_op) @operator
(assign_op) @operator
(fanout) @operator
["{" "}" "[" "]" "(" ")"] @punctuation.bracket
[";" ","] @punctuation.delimiter
