;; Generated by `cargo xtask gen-grammars` from the property ledger — do not edit.
;; Keyword predicates are ledger sets (types, properties, builders,
;; layouts); a new row appears here on regeneration or the drift test fails.

;; Comments, strings, numbers.
(comment) @comment
(string) @string
(escape) @string.escape
(number) @number
(hex_color) @constant

;; Identity bars: |type#id|.
(type_bars "|" @punctuation.bracket)
(id) @tag
(define_op) @operator

;; Built-in types (primitives + templates) vs user types.
((type) @type.builtin
  (#match? @type.builtin "^(alt|area|axis|badge|balloon|band|bars|block|box|breakline|bubble|caption|cell|centerline|chart|column|control|cyl|datum|diamond|dots|drawing|else|entity|feature-control|field|footer|footnote|frame|grid|group|halo|header|hex|hidden|hole|icon|image|line|loop|magnifier|mark|mindmap|note|opt|oval|page|path|pie|pitch-circle|plane|poly|projection|rect|row|sequence|shoulder|sign|sketch|slant|slice|surface-finish|table|threadline|tick|title-block|topic|zone)$"))
(type) @type

;; Property names: ledger rows strongly, others weakly.
((property) @property
  (#match? @property "^(activation|align|along|approved|at|author|axis|bars|baseline|break|categories|cell|characteristic|clearance|color|columns|curve|data|date|datums|density|department|direction|document-type|draw|drawing-number|facing|fill|fit|fn|font-family|font-size|font-style|font-weight|format|gap|gap-fill|gridlines|height|hint|hole|href|justify|labels|layer|layout|legend|letter-spacing|line-spacing|marker|marker-end|marker-start|material|max-width|mirror|modifiers|of|opacity|padding|path|pattern|pin|place|points|project|radius|range|reference|revision|revolve|rotate|routing|rows|samples|scale|shadow|sheet|sheet-number|side|skew|span|src|stack|status|step|stroke|stroke-style|stroke-width|symbol|text-decoration|text-shadow|text-transform|text-wrap|thread|ticks|title|tol|tooltip|translate|unit|value|width|zone)$"))
(property) @variable.other.member

;; CSS variables and the theme --vars.
(css_var) @variable

;; Value builders vs plain calls.
((call_name) @function.builtin
  (#match? @function.builtin "^(gradient|hatch|hsl|hsla|linear-gradient|oklch|radial-gradient|repeat|rgb|rgba)$"))
(call_name) @function

;; Enum value idents + layout names.
((value_ident) @constant.builtin
  (#match? @constant.builtin "^(flow|row|column|radial|bilateral|start|center|end|stretch|evenly|between|around|rows|columns|all|true|false|none|auto|solid|dashed|dotted|wavy|arrow|dot|circle|crow|many|datum|one|exactly-one|zero-or-one|one-or-many|zero-or-many|outlined|filled|rounded|sharp|log|linear|hover|always|top|bottom|left|right|over|chart|grid|pie|sequence|tree)$"))

;; Colour names.
((value_ident) @constant.builtin
  (#match? @constant.builtin "^(white|black|red|green|blue|gray|grey|crimson|orange|yellow|gold|silver|navy|teal|purple|pink|brown|cyan|magenta|lime|maroon|olive|cornflowerblue|currentColor|transparent)$"))

;; Classes, sides, operators, punctuation.
(class) @attribute
(side) @constant.builtin
(link_op) @operator
(assign_op) @operator
(fanout) @operator
["{" "}" "[" "]" "(" ")"] @punctuation.bracket
[";" ","] @punctuation.delimiter
