//! The Zed tree-sitter highlight query — `editors/zed/languages/lini/highlights.scm`.
//! The structural captures come from the `tree-sitter-lini` grammar; the word
//! sets ride `#match?` predicates, taken from [`super::vocab`] so they cannot
//! drift from the language.

use super::GENERATOR;
use super::vocab::{COLOR_NAMES, anchored_alt, builder_calls, properties, types, value_keywords};

/// The highlight query as `.scm` source.
pub fn zed_highlights() -> String {
    let mut out = String::new();
    out.push_str(&format!(
        ";; Generated by `{GENERATOR}` from the compiler's own tables — do not edit.\n\
         ;; The keyword predicates are those word sets (types, properties, builders,\n\
         ;; glyphs, layouts); a new row appears here on regeneration or the drift\n\
         ;; test fails.\n\n",
    ));

    out.push_str(";; Comments, strings, numbers.\n");
    out.push_str("(comment) @comment\n");
    out.push_str("(string) @string\n");
    out.push_str("(escape) @string.escape\n");
    out.push_str("(number) @number\n");
    out.push_str("(hex_color) @constant\n\n");

    out.push_str(";; Identity bars: |type#id|.\n");
    out.push_str("(type_bars \"|\" @punctuation.bracket)\n");
    out.push_str("(id) @tag\n");
    out.push_str("(define_op) @operator\n\n");

    out.push_str(";; Built-in types (primitives + templates) vs user types.\n");
    out.push_str(&format!(
        "((type) @type.builtin\n  (#match? @type.builtin \"{}\"))\n",
        anchored_alt(&types()),
    ));
    out.push_str("(type) @type\n\n");

    out.push_str(";; Property names: ledger rows strongly, others weakly.\n");
    out.push_str(&format!(
        "((property) @property\n  (#match? @property \"{}\"))\n",
        anchored_alt(&properties()),
    ));
    out.push_str("(property) @variable.other.member\n\n");

    out.push_str(";; CSS variables and the theme --vars.\n");
    out.push_str("(css_var) @variable\n\n");

    out.push_str(";; Value builders vs plain calls.\n");
    out.push_str(&format!(
        "((call_name) @function.builtin\n  (#match? @function.builtin \"{}\"))\n",
        anchored_alt(&builder_calls()),
    ));
    out.push_str("(call_name) @function\n\n");

    out.push_str(";; Enum value idents + layout names.\n");
    out.push_str(&format!(
        "((value_ident) @constant.builtin\n  (#match? @constant.builtin \"{}\"))\n\n",
        anchored_alt(&value_keywords()),
    ));

    out.push_str(";; Colour names.\n");
    out.push_str(&format!(
        "((value_ident) @constant.builtin\n  (#match? @constant.builtin \"{}\"))\n\n",
        anchored_alt(COLOR_NAMES),
    ));

    out.push_str(";; Classes, sides, operators, punctuation.\n");
    out.push_str("(class) @attribute\n");
    out.push_str("(side) @constant.builtin\n");
    out.push_str("(link_op) @operator\n");
    out.push_str("(assign_op) @operator\n");
    out.push_str("(fanout) @operator\n");
    out.push_str("[\"{\" \"}\" \"[\" \"]\" \"(\" \")\"] @punctuation.bracket\n");
    out.push_str("[\";\" \",\"] @punctuation.delimiter\n");

    out
}
