//! `cargo xtask extract-fonts` — regenerate the font artifacts from the
//! committed raw statics at `assets/fonts/raw/` [SPEC 5/6, ROADMAP 3.7]:
//!
//! - `src/font/metrics.rs`: per-glyph advance tables + ascent/descent/
//!   cap-height/upem, per family × weight {400, 500, 600, 700}. Generated
//!   Rust, always compiled in — layout must never vary by build flags.
//! - `assets/fonts/subset/*.ttf`: charset-subset faces for `--embed-font` /
//!   `--static`, gated behind the default-on `font` cargo feature. The
//!   `subsetter` crate is pinned at 0.1 deliberately: 0.2 strips `cmap`
//!   (PDF-only scope), which would break browser `@font-face` use; 0.1 keeps
//!   `cmap`/`name`/`OS2` and stable glyph ids. GSUB/GPOS are dropped — no
//!   kerning, matching the measurement model.

use std::fs;
use std::path::Path;
use std::process::{Command, ExitCode};

/// The subset charset [ROADMAP 3.7]: ASCII, Latin-1, Latin-Ext-A, General
/// Punctuation, and the drafting symbols lini composes (`⌀`; `° ± ×` are
/// Latin-1). One definition — the generated metrics file re-exports it for
/// the runtime lookup, so the tables and the index function can never drift.
const CHARSET: &[(u32, u32)] = &[
    (0x0020, 0x007E), // ASCII
    (0x00A0, 0x00FF), // Latin-1 Supplement
    (0x0100, 0x017F), // Latin Extended-A
    (0x2000, 0x206F), // General Punctuation
    (0x2300, 0x2300), // ⌀ DIAMETER SIGN
];

const WEIGHTS: [(&str, u16); 4] = [
    ("Regular", 400),
    ("Medium", 500),
    ("SemiBold", 600),
    ("Bold", 700),
];

/// (family dir, file stem, const prefix, is_mono)
const FAMILIES: [(&str, &str, &str, bool); 2] = [
    ("Google_Sans_Code", "GoogleSansCode", "MONO", true),
    ("Google_Sans", "GoogleSans", "PROP", false),
];

/// Shipped payload ceiling — trim charset first, weights second [PLAN M5].
const BUDGET: usize = 600 * 1024;

fn charset_chars() -> impl Iterator<Item = char> {
    CHARSET
        .iter()
        .flat_map(|&(a, b)| a..=b)
        .filter_map(char::from_u32)
}

pub fn extract_fonts() -> ExitCode {
    let root = Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("workspace root")
        .to_path_buf();
    let subset_dir = root.join("assets/fonts/subset");
    fs::create_dir_all(&subset_dir).expect("create subset dir");

    let mut metrics = String::from(
        "//! GENERATED by `cargo xtask extract-fonts` — do not edit.\n\
         //!\n\
         //! Per-glyph advance tables and vertical metrics for the two bundled\n\
         //! families × weights 400/500/600/700, in font units [SPEC 5]. Always\n\
         //! compiled in: layout must never vary by build flags. An advance of 0\n\
         //! marks a glyph the face does not cover (the runtime falls back).\n\n\
         use super::Face;\n\n",
    );
    metrics.push_str(
        "/// The subset charset, as inclusive codepoint ranges — the advance\n\
         /// tables index across these in order.\n\
         pub const CHARSET: &[(u32, u32)] = &[\n",
    );
    for &(a, b) in CHARSET {
        metrics.push_str(&format!("    (0x{a:04X}, 0x{b:04X}),\n"));
    }
    metrics.push_str("];\n");

    let mut total = 0usize;
    for (dir, stem, prefix, is_mono) in FAMILIES {
        let mut face_names = Vec::new();
        for (weight_name, weight) in WEIGHTS {
            let path = root.join(format!("assets/fonts/raw/{dir}/{stem}-{weight_name}.ttf"));
            let data = match fs::read(&path) {
                Ok(d) => d,
                Err(e) => {
                    eprintln!("cannot read {}: {e}", path.display());
                    return ExitCode::FAILURE;
                }
            };
            let face = ttf_parser::Face::parse(&data, 0).expect("parse raw font");
            let upem = face.units_per_em();
            let ascent = face.ascender();
            let descent = face.descender();
            let cap_height = face
                .capital_height()
                .expect("raw face carries a cap height");

            // Advances, in font units; 0 = not covered by this face.
            let mut advances: Vec<u16> = Vec::new();
            let mut mappings: Vec<(u32, u16)> = Vec::new();
            for ch in charset_chars() {
                match face.glyph_index(ch) {
                    Some(gid) => {
                        let adv = face.glyph_hor_advance(gid).unwrap_or(0);
                        advances.push(adv);
                        mappings.push((ch as u32, gid.0));
                    }
                    None => advances.push(0),
                }
            }
            let glyph_ids: Vec<u16> = mappings.iter().map(|&(_, g)| g).collect();

            // The mono invariant [SPEC 5]: every covered glyph advances exactly
            // 0.6 em, at every weight — the old flat estimate stays exact.
            if is_mono {
                let expect = (upem as f64 * 0.6).round() as u16;
                for (ch, &adv) in charset_chars().zip(&advances) {
                    assert!(
                        adv == 0 || adv == expect,
                        "{stem}-{weight_name}: U+{:04X} '{ch}' advances {adv}, expected {expect} (0.6 em)",
                        ch as u32,
                    );
                }
            }

            let name = format!("{prefix}_{weight}");
            metrics.push_str(&format!(
                "\npub const {name}: Face = Face {{\n    \
                 upem: {upem},\n    \
                 ascent: {ascent},\n    \
                 descent: {descent},\n    \
                 cap_height: {cap_height},\n    \
                 advances: &[\n"
            ));
            for chunk in advances.chunks(12) {
                let row: Vec<String> = chunk.iter().map(u16::to_string).collect();
                metrics.push_str(&format!("        {},\n", row.join(", ")));
            }
            metrics.push_str("    ],\n};\n");
            face_names.push(name);

            // The subset TTF: charset glyphs (+ .notdef, always glyph 0).
            let profile = subsetter::Profile::pdf(&glyph_ids);
            let sub = subsetter::subset(&data, 0, profile).expect("subset font");
            let sub = rebuild_cmap(&sub, &mappings);
            let out = subset_dir.join(format!("{stem}-{weight_name}.ttf"));
            fs::write(&out, &sub).expect("write subset");
            total += sub.len();
            eprintln!(
                "{stem}-{weight_name}: {} glyphs, subset {} KB (raw {} KB)",
                glyph_ids.len(),
                sub.len() / 1024,
                data.len() / 1024,
            );
        }
        metrics.push_str(&format!(
            "\npub const {prefix}: [&Face; 4] = [&{}];\n",
            face_names.join(", &")
        ));
    }

    eprintln!("total subset payload: {} KB", total / 1024);
    assert!(
        total <= BUDGET,
        "subset payload {} KB exceeds the {} KB budget",
        total / 1024,
        BUDGET / 1024,
    );

    let dest = root.join("src/font/metrics.rs");
    write_metrics(&dest, metrics)
}

/// `subsetter` 0.1 passes the original `cmap` through verbatim, so a char the
/// raw face covers but the subset dropped would map to an emptied, zero-advance
/// glyph — rendering *invisibly* in a browser instead of falling through to
/// the next font in the stack. Rebuild a minimal format-12 `cmap` covering
/// exactly the kept charset: everything else misses the cmap, and per-glyph
/// system fallback works as [SPEC 17] promises.
fn rebuild_cmap(font: &[u8], mappings: &[(u32, u16)]) -> Vec<u8> {
    // Coalesce (codepoint, gid) pairs into format-12 groups: consecutive
    // codepoints with consecutive glyph ids share a group.
    let mut groups: Vec<(u32, u32, u32)> = Vec::new();
    for &(cp, gid) in mappings {
        match groups.last_mut() {
            Some((start, end, start_gid))
                if cp == *end + 1 && gid as u32 == *start_gid + (*end - *start) + 1 =>
            {
                *end = cp;
            }
            _ => groups.push((cp, cp, gid as u32)),
        }
    }

    // cmap: header (version 0, one table), one encoding record (Windows /
    // full-Unicode 3.10), one format-12 subtable.
    let mut cmap = Vec::new();
    push16(&mut cmap, 0); // version
    push16(&mut cmap, 1); // numTables
    push16(&mut cmap, 3); // platformID: Windows
    push16(&mut cmap, 10); // encodingID: full Unicode
    push32(&mut cmap, 12); // subtable offset
    push16(&mut cmap, 12); // format
    push16(&mut cmap, 0); // reserved
    push32(&mut cmap, 16 + groups.len() as u32 * 12); // length
    push32(&mut cmap, 0); // language
    push32(&mut cmap, groups.len() as u32);
    for (start, end, gid) in groups {
        push32(&mut cmap, start);
        push32(&mut cmap, end);
        push32(&mut cmap, gid);
    }

    // Reassemble the sfnt with the new cmap: same tables, recomputed offsets,
    // checksums, and head.checkSumAdjustment.
    let num_tables = read16(font, 4) as usize;
    let mut tables: Vec<([u8; 4], Vec<u8>)> = Vec::with_capacity(num_tables);
    for i in 0..num_tables {
        let rec = 12 + 16 * i;
        let tag: [u8; 4] = font[rec..rec + 4].try_into().unwrap();
        let off = read32(font, rec + 8) as usize;
        let len = read32(font, rec + 12) as usize;
        let mut data = if &tag == b"cmap" {
            cmap.clone()
        } else {
            font[off..off + len].to_vec()
        };
        if &tag == b"head" {
            data[8..12].fill(0); // zero checkSumAdjustment before checksumming
        }
        tables.push((tag, data));
    }

    let mut out = Vec::new();
    let n = tables.len() as u16;
    let entry_selector = 15 - n.leading_zeros() as u16; // floor(log2 n)
    let search_range = 16 << entry_selector;
    push32(&mut out, 0x0001_0000); // sfnt version: TrueType
    push16(&mut out, n);
    push16(&mut out, search_range);
    push16(&mut out, entry_selector);
    push16(&mut out, n * 16 - search_range);

    let mut offset = 12 + 16 * tables.len();
    let mut head_offset = 0;
    for (tag, data) in &tables {
        out.extend_from_slice(tag);
        push32(&mut out, table_checksum(data));
        push32(&mut out, offset as u32);
        push32(&mut out, data.len() as u32);
        if tag == b"head" {
            head_offset = offset;
        }
        offset += data.len().next_multiple_of(4);
    }
    for (_, data) in &tables {
        out.extend_from_slice(data);
        out.resize(out.len().next_multiple_of(4), 0);
    }

    let adjustment = 0xB1B0_AFBAu32.wrapping_sub(table_checksum(&out));
    out[head_offset + 8..head_offset + 12].copy_from_slice(&adjustment.to_be_bytes());
    out
}

fn table_checksum(data: &[u8]) -> u32 {
    data.chunks(4).fold(0u32, |sum, c| {
        let mut w = [0u8; 4];
        w[..c.len()].copy_from_slice(c);
        sum.wrapping_add(u32::from_be_bytes(w))
    })
}

fn push16(out: &mut Vec<u8>, v: u16) {
    out.extend_from_slice(&v.to_be_bytes());
}
fn push32(out: &mut Vec<u8>, v: u32) {
    out.extend_from_slice(&v.to_be_bytes());
}
fn read16(data: &[u8], at: usize) -> u16 {
    u16::from_be_bytes(data[at..at + 2].try_into().unwrap())
}
fn read32(data: &[u8], at: usize) -> u32 {
    u32::from_be_bytes(data[at..at + 4].try_into().unwrap())
}

fn write_metrics(dest: &Path, metrics: String) -> ExitCode {
    fs::create_dir_all(dest.parent().unwrap()).expect("create src/font");
    fs::write(dest, metrics).expect("write metrics");
    let fmt = Command::new("rustfmt").arg(dest).status();
    if !fmt.map(|s| s.success()).unwrap_or(false) {
        eprintln!("warning: rustfmt on {} failed", dest.display());
    }
    eprintln!("wrote {}", dest.display());
    ExitCode::SUCCESS
}
